### PR TITLE
Adding rel="noopener" for fixing cross-origin links and improving performance

### LINKED ISSUE #1406: Links to cross-origin Destinations are unsafe
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Some cross-links origin are unsafe which decrease performance and increase security vulnerabilities. Learn more.

**Will work on the issue:**
yes

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1406 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Adding rel="noopener" in anchor tags which has target="blank" attribute for improving performance

-  https://pr-1407-fossasia-susper.surge.sh

- ### For Reference
  
screenshot-developers google com-2019 01 13-14-26-37

screenshot-developers google com-2019 01 13-14-29-14

### CODE REVIEW

**Comment by subhahu123** [comment]
@praveenojha33  @simsausaurabh  @shreyanshdwivedi  please review

**Review by rajvaibhavdubey — APPROVED** [review]
`rel=noopener` LGTM :+1: .
[reference](https://developers.google.com/web/tools/lighthouse/audits/noopener)

**Review by praveenojha33 — COMMENTED** [review]
This attribute has been added to fossasia projects links only. If it is useful I think we can extend it to other search links in project.

**Comment by subhahu123** [comment]
@praveenojha33  Please check the above refered link given by raj vaibhav dubey

**Review by shreyanshdwivedi — APPROVED** [review]
This is something new and interesting. LGTM :+1:

**Review by championpaddler — APPROVED** [review]
@subhahu123  LGTM :+1:

**Comment by rajvaibhavdubey** [comment]
> This attribute has been added to fossasia projects links only. If it is useful I think we can extend it to other search links in project.

I think it would be better if it is added to all the external links on the project @praveenojha33

**Comment by subhahu123** [comment]
> > This attribute has been added to fossasia projects links only. If it is useful I think we can extend it to other search links in project.
> 
> I think it would be better if it is added to all the external links on the project @praveenojha33

@rajvaibhavdubey  it should be added only to those links which opens in a new `Tab` means which contains the target="blank" attribute

**Review by simsausaurabh — APPROVED** [review]

**Review by sakshee-19 — APPROVED** [review]

**Pull request merged**
