### PR TITLE
Susper logo wrong redirect fixed

### LINKED ISSUE #1397: Susper logo button on homepage wrong redirect
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

It redirects to https://https//github.com/fossasia/susper.com

**Expected behavior:**

Should redirect to https://github.com/fossasia/susper.com

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
Fixes #1397 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Susper logo wrong redirect fixed.
- Open in new tab added.

- https://pr-1402-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by subhahu123** [comment]
but it is working fine in surge link 
screenshot from 2019-01-11 16-08-27

**Comment by rajvaibhavdubey** [comment]
@subhahu123 becuase I fixed it that's why it's working. Check it on susper.com .

**Comment by subhahu123** [comment]
Susper.com is not workings because
master branch is some commits behind the development

**Comment by shreyanshdwivedi** [comment]
I agree to @subhahu123

**Comment by rajvaibhavdubey** [comment]
@subhahu123 my bad, I just forgot about it.

**Pull request closed without merging**
