### PR TITLE
Fixes #718, margin for autocorrect and results fixed

### LINKED ISSUE #718: Fix margin for autocorrect and results
**Actual Behaviour**

Results for videos is skewed. Auto correct alignment is skewed everywhere

**Expected Behaviour**

Correctly align all components

**Screenshots of the issue**
image

Working on this :+1:

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #718 

Changes: margin for auto correct and results fixed

Demo Link: [https://marauderer97.github.io/susper.com](https://marauderer97.github.io/susper.com)

Screenshots for the change: 
image
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
Aligned at all sizes 
image
image
@harshit98 @nikhilrayaprolu Please review

**Comment by harshit98** [comment]
@Marauderer97 It would be better if you align the results feed content towards a little bit right side. Follow up my comment here #720

**Comment by Marauderer97** [comment]
@harshit98 I am confused. Are you talking about small screen dimensions? Or very large screen dimension? Like I mentioned in #720 won't the alignment with the search bar get disturbed if I do that?

**Comment by Marauderer97** [comment]
@harshit98, for small screens is this much margin alright?
image

**Comment by harshit98** [comment]
Okay looks good.

**Pull request merged**
