### PR TITLE
Fixes #378, Search bar at center of page for all sizes, made responsive

### LINKED ISSUE #378: Search bar is improperly placed on search page and home page
image
image

Details:
Screen Resolution : 1920*1080

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #378 

Changes: Makes search bar position responsive, for all screen sizes

Demo Link: [Here](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 
AT size 1920x900
screen shot 2017-06-03 at 19 18 25

image
image
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@nikhilrayaprolu @harshit98 @isuruAb Kindly review :)

**Comment by harshit98** [comment]
There is some issue with `search button` responsiveness. Open up a new issue regarding that. : )

**Comment by Marauderer97** [comment]
@sandeepm96 Please check now:
image
image
image
image

**Comment by sandeepm96** [comment]
Looks good @Marauderer97  👍

**Pull request merged**
