### PR TITLE
Addresses #733 sidebar is showing links

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
Fixes issue #733

Changes: removed link for undefined author

Demo Link: http://susper-pr-746.herokuapp.com/

Screenshots for the change: 
image

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@mariobehling sorry for this, I didn't understand what you mean by status bar, can you please add a screenshot of what you are expecting.

**Comment by mariobehling** [comment]
@nikhilrayaprolu A simple Google search for "status bar" will yield a result.

Scrolling over the links in the sidebar does not show a preview of the link address. (And actually most links on the sidebar don't yield a result e.g. search fossasia and click on Michael Christen).

screenshot from 2017-08-15 11-53-15

**Comment by nikhilrayaprolu** [comment]
screen shot 2017-08-17 at 4 59 43 pm
@mariobehling showing the status bar now. 
secondly regarding some links not showing up results, it is a server side issue. since we get modifiers to be used for the facets from the serverside, and we just use these modifiers. For some results these modifiers are not working properly.

**Comment by mariobehling** [comment]
Ok, thank you. Let's iterate from here. Cheers.

**Pull request merged**
