### PR TITLE
Fixes:#952Made the footer positioned ath the bootom of the page in contact,abou…

### PR DESCRIPTION
**Pull request by sathiraumesh**
…t and searchsetting pages

Fixes: #952

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

https://pr-953-fossasia-susper.surge.sh

#### Changes proposed in this pull request:

Changes were made to css and html in about ,contact and search settings pages

  src/app/about/about.component.css
  src/app/about/about.component.html
  src/app/contact/contact.component.css
  src/app/contact/contact.component.html
  src/app/searchsettings/searchsettings.component.css
  src/app/searchsettings/searchsettings.component.html

screen shot 2018-03-20 at 11 01 38 am

screen shot 2018-03-20 at 11 01 20 am

### CODE REVIEW

**Comment by sathiraumesh** [comment]
Thanks 👍

**Comment by praveenojha33** [comment]
@sathiraumesh I think you have disturbed responsiveness in some mobile devices. Please fix this 
sathira

**Comment by praveenojha33** [comment]
Yes the problem persist in chrome,I have also checked using Firefox and for some screen sizes "Save" and "Cancel" button are completely hidden.
p1

**Comment by sathiraumesh** [comment]
praveenojha33

can you recheck on this beacuse mine seems to be fine

**Comment by duttaditya18** [comment]
@sathiraumesh Yup! It does seem fine here as well.

**Comment by sathiraumesh** [comment]
Do you have any suggestions for this issue

**Comment by harshit98** [comment]
Hi @sathiraumesh 👋 what's the status of this PR?

**Comment by sathiraumesh** [comment]
There seems to be a small problem in the search settings page but the other too pages seems to be working fine  i can revert the changes to the search settings page because there is issue that we have to look for more details

**Comment by sathiraumesh** [comment]
harshit98 i reverted the changes in the search settings page now its okay to merge the pr I will make the changes to search settings using another pr.
Only changes to about and contact page exsists

**Comment by praveenojha33** [comment]
Hello @sathiraumesh Please write commit message properly. Correct typos from commit message.

**Comment by sathiraumesh** [comment]
ok

**Pull request merged**
