### PR TITLE
Fixes #725, Aligning the Analytics box at sizes less than 1034 px

### LINKED ISSUE #725: Better Alignment of Infobox and Analytics Box
The responsiveness of Infobox and Alignment box has to be improved and made similar to Google and loklak
Currently it is breaking at certain dimensions

**Screenshots of the issue**
In Firefox
image

In Chrome,(1216px)
image

Working on this :+1:

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #725 
Changes: Aligning the Analytics box at sizes less than 1034 px

Demo Link: [https://marauderer97.github.io/susper.com/](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 
before:
image

after:
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Alright will change. @harshit98 Working on it. There are some problems with ids and classes. Trying to figure out a work around

**Comment by Marauderer97** [comment]
@harshit98 Please check now . It is working for very large sizes too.
image
 @nikhilrayaprolu done

**Comment by mariobehling** [comment]
Please reduce the distance between search results and the box. Compare to below.

screenshot from 2017-08-11 21-38-25

**Comment by mariobehling** [comment]
The width and style of our boxes is still very different to the sample of Google.

screenshot from 2017-08-11 21-51-59

**Comment by Marauderer97** [comment]
@mariobehling Please check now
I have made the following changes:
1. Google uses sizes 3 different sizes for >1200px, 1200-1280px and <1200px. I have copied the sizes for both boxes exactly.
2. Google maintains a margin of exactly 36px between the results and the box at all sizes, I copied that exactly too.

**Comment by mariobehling** [comment]
Ok, I cannot see this at the test link. As we are short of time, I will follow up on the live site, if there is anything left. Cheers.

**Pull request merged**
