### PR TITLE
On help page when hover on close button cursor is pointer

### LINKED ISSUE #1434: Cursor should be pointer when hover on close button
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
when hover on close button on help page the cursor is default

**Expected behavior:**
when hover on close button on help page the cursor should be pointer

**Screenshots of the issue:**
cursor

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #1434 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

-When hover on close button of help page cursor is pointer

- https://pr-1435-fossasia-susper.surge.sh

-
cursor

### CODE REVIEW

**Review by neeraj3029 — APPROVED** [review]
Fix the travis build, rest looks good.

**Comment by samagragupta** [comment]
@praveenojha33 @Orbiter @mariobehling Please review.

**Review by sakshee-19 — APPROVED** [review]

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
Please fix Travis.

**Review by simsausaurabh — COMMENTED** [review]
FIx travis issue, then it will be good to go.

**Comment by samagragupta** [comment]
@simsausaurabh @praveenojha33 Fixed the travis

**Review by sakshee-19 — APPROVED** [review]

**Review by simsausaurabh — APPROVED** [review]

**Pull request merged**
