### PR TITLE
Fixes #742 Infobox and Analytics box changed for chrome only

### LINKED ISSUE #742: Boxes disturbed in Google chrome
**Actual Behaviour**

The Infobox and Analytics box are not properly placed in Google Chrome, though they are correctly positioned at the same dimension in Firefox. 

**Expected Behaviour**
We need to write browser specific CSS to fix this problem.

**Screenshots of the issue**
(Both taken at 1289px)
image
image
Making a PR at once

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #742
Changes: Infobox and Analytics box changed for chrome only
I have replicated what Google does. 
Google in Firefox at 1290px
image
Susper in Firefox at 1290px
image
Google in Chrome at 1290px
image
Susper in Chrome at 1290px
image

NOTE: Also applied the exact same CSS for the Analytics Box

Demo Link: [https://marauderer97.github.io/susper.com/](https://marauderer97.github.io/susper.com/)

### CODE REVIEW

**Comment by Marauderer97** [comment]
Codacy is objecting to using a seperate tag for Chrome but this was the best solution I could find online and in the documentation. Please suggest if there is a better way.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97  demolink is not working for me,
image

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Those are the errors because images are not being loaded.Also there seems to be some error with chart.js, even in susper.com. My local distribution is working fine. Can you please deploy heroku for this PR. Actually I am not able to see results for any github link
image

**Comment by nikhilrayaprolu** [comment]
http://susper-pr-743.herokuapp.com/ use this link

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Thank you. The heroku link is working
image

**Comment by nikhilrayaprolu** [comment]
image
this is in iphone 6, iphone 6 shows infobox in google like this. Can you implement similarly for susper.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Alright, I will raise an issue for mobile compatability of infobox and work on it :+1:

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
