### PR TITLE
Fixes #381 Match alignment of text with market leader

### LINKED ISSUE #381: Match alignments of text with market leader
Text alignments are not matching market leader.

Compare Susper
screenshot from 2017-05-30 19-58-00

With this..
screenshot from 2017-05-30 19-57-36

### PR DESCRIPTION
**Pull request by harshit98**
Closes #381

Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>

Screenshot -

Before -
screenshot from 2017-05-31 12-20-49

After-
screenshot from 2017-05-31 12-20-27

Google -
screenshot from 2017-05-31 12-26-33

Kindly review @nikhilrayaprolu @Marauderer97

### CODE REVIEW

**Comment by harshit98** [comment]
@sandeepm96 No. But I'll separately open up issue for that as it will require some work like matching it will the tabs. :)

**Comment by harshit98** [comment]
@Marauderer97 done. Updated preview link <a href="https://harshit98.github.io/susper.com/">here</a>.

**Comment by Marauderer97** [comment]
@harshit98 Good job! but please fix this glitch too.
image

**Comment by harshit98** [comment]
@Marauderer97 I found that this glitch is on Chrome. On Firefox it works fine. Maybe we can open up an issue separately for that ? Because it seems the issue is with `search button`

screenshot from 2017-06-03 19-23-30

**Comment by Marauderer97** [comment]
@harshit98 What is the problem with the search button? I am slightly  confused. Do you mean it is not responsive? Also are you sure that on Firefox it is completely responsive, try these dimensions please :)
image

**Comment by Marauderer97** [comment]
@harshit98  Please include updated screenshots :smile:

**Comment by harshit98** [comment]
I'll open a new PR regarding this. After merging of this PR #400 , I'll fix it according to latest changes so that the issue does not arise again.

**Pull request closed without merging**
