### PR TITLE
Fixing Result numbers not displayed ( for images section )

### LINKED ISSUE #1136: Result numbers not displayed and other tabs shortly load "all" tab info
1. The result numbers are not displayed on:
* Image Tab
* News Tab

2. When a tab is chosen shortly the number from the "all page" is displayed and then the real number. Expected do not load data of "all" first and then filtered data. Only load the data relevant for the tab.

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1136 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Adding div container for adding total results for images section 

- https://pr-1422-fossasia-susper.surge.sh

- 
screenshot_2019-01-23 susper - decentral search engine

### CODE REVIEW

**Comment by subhahu123** [comment]
@rajvaibhavdubey @shreyanshdwivedi @praveenojha33 
please review

**Review by praveenojha33 — COMMENTED** [review]
Please compare it with Google, we do not have to show it for Image Section.

**Comment by subhahu123** [comment]
> Please compare it with Google, we do not have to show it for Image Section.

ok i was just doing the asked changes in isssue #1136

**Review by sakshee-19 — APPROVED** [review]

**Comment by simsausaurabh** [comment]
@subhahu123 I guess we do not need to show it for now. Lets keep it on hold for sometime, we'll update the information for this. Closing this for now. Follow up once confirmed.

**Pull request closed without merging**
