### PR TITLE
Fixes #46, search bar fixed and changes in styling

### LINKED ISSUE #46: Search bar on results page is not working
The search bar on the results page seems to have a bug. It does nothing on clicking the search button.

### PR DESCRIPTION
**Pull request by Marauderer97**
This PR fixes the following issues:
1. Search-bar on results page is working.Additionally it works on pressing enter.
2. Results page has been styled to resemble Google:
Before:
image
image
Now:
image
image
3. Help icon mentioned in issue #45 has been removed temporarily, as it does not match with the site design of google

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 great work .can you please keep the help button back.  you could replace the help button with 'google apps' icon as shown
image

**Comment by mariobehling** [comment]
Thanks! Let's iterate from here.

**Comment by mariobehling** [comment]
@Marauderer97 Thank you. Please help to resolve conflicts.

**Comment by Marauderer97** [comment]
@mariobehling Conflicts have been resolved. 
@nikhilrayaprolu I can add the apps button as you suggested, but what next? What will the menu contain? Apps related to Susper, or help options? @mariobehling Any suggestions on this? I will then make a PR adding the button along with its menu :smile:

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 You can make separate icons for each subtopic in help page and make the help icons look like google apps . for now you could use matching material icons ( https://material.io/icons/ ) for the help pages. For now raise an issue regarding the help icon , lets have a complete discussion there , and then finalize upon this.
and Thank you for your work :smile:

**Pull request merged**
