### PR TITLE
Fixes #463, Changes pagination bar in Susper to resemble market leader

### LINKED ISSUE #463: Match bottom bar links to search results pages closer to market leader
Please follow the design of the market leader for the search result pages.
screenshot from 2017-06-09 01-23-24

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #463 

Changes:Changes pagination bar in Susper to resemble market leader

Demo Link: [Here](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 

Before:
image
After:
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 @nikhilrayaprolu @sandeepm96 @isuruAb Please review :)

**Comment by harshit98** [comment]
@Marauderer97 Preview link is not working properly. When I attempt a search, it hangs up.

**Comment by Marauderer97** [comment]
@harshit98 It is working properly. I think you need to allow loading unsafe scripts
image

**Comment by Marauderer97** [comment]
@mariobehling Please check now
image
image

**Comment by Marauderer97** [comment]
@harshit98 Sorry, the link had the wrong branch, 
Please check again [Here](https://marauderer97.github.io/susper.com/)

**Comment by isuruAb** [comment]
@Marauderer97  please check why the codacy is failing

**Pull request merged**
