### PR TITLE
Fixes #1000: Different results open in newtab without flickering

### LINKED ISSUE #1000: Allow user to open different result section in New Tab
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Currently the user cannot open different result section like `Image` , `Video` etc in New Tab by right click.

**Expected behavior:**
Allow user to open the results in new tab.

**Screenshots of the issue:**
image

### PR DESCRIPTION
**Pull request by praveenojha33**
Fixes #1000 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Different results open in newtab without flickering

- https://pr-1103-fossasia-susper.surge.sh

image

### CODE REVIEW

**Comment by praveenojha33** [comment]
@simsausaurabh Currently if we are on a tab then also on right click on that tab it will ask to open it in new tab. I will fix this issue in another patch.

**Comment by simsausaurabh** [comment]
Is it fine that on opening Tools and Settings tab I am getting redirected to home page. If followed similar to Google, it can be removed to open Tools and Settings in new tab? What are your views on it?

**Comment by praveenojha33** [comment]
@simsausaurabh Yeah it can be done, I will discuss it with mentor and then we can work on it.

**Comment by mariobehling** [comment]
Yes, please follow Google where-ever possible. Cheers.

**Pull request merged**
