### PR TITLE
Fixes #509: Improve dropdown menu

### LINKED ISSUE #509: Implement better dropdown menu
The dropdown menu has issues. Please improve the following:
* make the distance to the dropdown more natural
* match the size and design of the market leader
* use colorful logo
* Add the following services below a horizontal line after the first section using the logos of the services:
   * FOSSASIA - fossasia.org
   * loklak - loklak.net
   * SUSI.AI - chat.susi.ai
   * eventyay - eventyay.com
* Add a more link on the bottom section to "labs.fossasia.org"

screenshot from 2017-06-17 16-40-32

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #509 

Changes: 
- Created a component for dropdown to maintain the code easily and tests can be written for it so that front-end issues won't rise up again.
- Brought the drop down menu, on homepage as well similar to Google.

Demo Link: http://harshit98.github.io/susper.com/

Screenshots for the change: 

screenshot from 2017-06-21 15-05-20

screenshot from 2017-06-21 15-05-28

screenshot from 2017-06-21 15-05-44

### CODE REVIEW

**Comment by harshit98** [comment]
@Marauderer97 

- Regarding dropdown being disappear on viewport : 760px, kindly follow up issue here : #524 . This will be fixed there. I have worked as per issue and thought it would be best time to refactor result's component as well. See #53 .
- Center aligning the text, I'll do the changes.
- I'll change the gap as you suggested for `more on..`
- Regarding Google's dropdown, they use tooltip. Implementing a tooltip with dropdown feature will take a lot of time. If you still not agree with me : Can you suggest me how should I proceed with it ? Or maybe you can create an issue once this PR gets merged, and open up a PR for that (because this PR is too big at present). It would be great!
- I'll improve the padding between the areas of horizontal line.
- I'll add the hover feature too as you suggested.

> Also notice that the cursor does not change to a pointer on hover in Google, while it does in Susper

No. Kindly check again. Google also changes cursor to pointer on hover.
- Regarding padding around edges - I have followed market leader design.
screenshot from 2017-06-22 00-46-45
screenshot from 2017-06-22 00-47-04

> Different design of more message

Kindly follow up the issue.

**Comment by Marauderer97** [comment]
@harshit98
- Pointer my bad, I re-checked, you are right
- We can raise a separate issue for tooltip like suggested
- Regarding padding around the edges, I still think Google, has slightly more(not values, visibility wise, but your call)
-  I have followed up the issue, by different design of more message, I don't mean different content, I mean design. The more message in Google is designed differently(Not in blue etc.)

**Comment by mariobehling** [comment]
@harshit98 Could you please check if you can find another "Contact Icon". The phone feels a bit confusing as contact isn't mainly about phone. We actually don't want anyone to call us.

**Comment by harshit98** [comment]
@mariobehling done! changed the contact logo as you said. 

@Marauderer97 done the changes you requested. If you find some more issues, kindly open them up as separate issues. Already this PR has become big.

Screenshot after changes : 

screenshot from 2017-06-22 15-44-06

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
