### PR TITLE
contact us page || map add

### LINKED ISSUE #1459: No map at contact us page
**I'm submitting a ...**
- [x] feature request

**Current behavior:**
There is no map showing the location on the contact us page
**Expected behavior:**
There should be a map which shows the location.

**Will work on the issue:**
YES

### PR DESCRIPTION
**Pull request by Parth910**
Fixes #1459  

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [X] I have added necessary documentation (if appropriate)
- [X] Added Surge preview link

#### Changes proposed in this pull request:

- Map has been add at contact us page

- https://pr-1463-fossasia-susper.surge.sh

- pr-1463-fossasia-susper

### CODE REVIEW

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
I do not know whether is it appropriate to use Google Service here. @AakashMallik @shreyanshdwivedi @mariobehling Please review this. I do not think using any other service is appropriate.

**Comment by Parth910** [comment]
@praveenojha33  can we use an image for preview and use google maps link instead of using Google API?

**Comment by simsausaurabh** [comment]
@praveenojha33 I guess we can try it for a while, since its open to use.

**Review by praveenojha33 — APPROVED** [review]
@simsausaurabh I am approving it then. But I think other mentors should also review it once.

**Comment by simsausaurabh** [comment]
@praveenojha33 Yes.

**Comment by mariobehling** [comment]
Let's avoid a map here. We always need API keys and if it is not really necessary should avoid integrating other services.

**Pull request closed without merging**
