### PR TITLE
Reopened PR: Adding the functionality of sorting searchs by dates

### PR DESCRIPTION
**Pull request by Heredroky**

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you, please provide a link to your github page to test in the description (not the repository, the test page).

**Comment by mariobehling** [comment]
Does not seem to work here: http://Heredroky.github.io/susper.com

Cannot see results.

**Comment by Heredroky** [comment]
@mariobehling Yes, it doesn't show the results, but locally it did, and the functionality I've added worked very good :)

**Comment by Heredroky** [comment]
@mariobehling Believe me, it will work 😄

**Comment by mariobehling** [comment]
Clicking on date option several times results in additional "/date"

screenshot from 2016-12-12 01-12-22

**Comment by mariobehling** [comment]
* Text not aligned in the same way
* Clicking on "Search Tools" again should show the relevant search highlighted, e.g. "Search by Date"

screenshot from 2016-12-12 01-23-35

**Comment by Heredroky** [comment]
@mariobehling Ok, I will fix it

**Comment by Heredroky** [comment]
@mariobehling Hi! 😄 , I fixed the problems. Tell me what do you think

**Pull request merged**
