### PR TITLE
Sorting searchs by date

### PR DESCRIPTION
**Pull request by Heredroky**

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks!

Please provide a screenshot and link to your github test page for reviews.

Please also provide a description mentioning the relevant issue.

**Comment by Heredroky** [comment]
Repo: https://github.com/Heredroky/susper.com
screen shot 2016-12-09 at 9 17 33 am
screen shot 2016-12-09 at 9 17 43 am
screen shot 2016-12-09 at 9 17 50 am

Here, I made the functionality for the "Sort by Date" in the search tools, in the issue #19 you told me to do that.

Cheers!

**Comment by Heredroky** [comment]
@mariobehling What do you think about the changes I did?

**Comment by mariobehling** [comment]
For a common understanding the test page would be here: http://Heredroky.github.io/susper.com

Please add it in future. I cannot see it working here.

**Pull request closed without merging**
