### PR TITLE
Addresses #132 Added Codecov

### PR DESCRIPTION
**Pull request by harshit98**
Added codecov as coverage tool. @nikhilrayaprolu I have done some work again on it, you can help. : )

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
Travis is failing.

**Comment by harshit98** [comment]
Yes, @niranjan94 I have kept those points in my mind. But let the work gets finished, I'll squash the commits. Can you help me out with this? : ) You can check my latest commit report and the error I'm facing.

**Comment by mariobehling** [comment]
Please resolve conflicts.

Please avoid the issue number in the commit message, but do add the issue number in the description to make it easier for reviewers and speed up the process. 

Could you read my post about best practices, please? http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by nikhilrayaprolu** [comment]
@harshit98 what is the reason behind using docker in Travis?

**Comment by harshit98** [comment]
@nikhilrayaprolu I was trying to pass the reports through docker container so that the reports appear in comments. I followed <a href="https://github.com/codecov/support/wiki/Testing-with-Docker">Testing docker with Codecov</a>. But, later on I ended up with an parsing error.

`docker: Error parsing reference: "..." is not a valid repository/tag.`
So, I created a new Dockerfile. You can read the whole issue <a href="http://stackoverflow.com/questions/43330235/passing-reports-through-docker-in-codecov-gives-error">here</a>.

**Comment by mariobehling** [comment]
Apparently we are not using Docker at the moment. Do I understand correctly, you created a docker file to pass tests?

**Comment by harshit98** [comment]
@mariobehling Yes, and to pass the coverage report and make it appear in comments- just like <a href="https://github.com/fossasia/open-event-orga-server/pull/3516">here</a>.

**Comment by nikhilrayaprolu** [comment]
@harshit98  can't we implement it without using docker?

**Comment by harshit98** [comment]
@nikhilrayaprolu Yes we can. I have done the work without using docker also, my previous- <a href="https://github.com/fossasia/susper.com/pull/133/files">here</a>.

**Pull request merged**
