### PR TITLE
Footer fixed at bottom

### LINKED ISSUE #1199: Footer should be at the bottom
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Footer should be at the bottom, it looks a bit out of the place

**Screenshots of the issue:**

screenshot from 2018-10-31 23-12-42

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
Fixes #1199 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- The footer bar of susper has been fixed at the bottom with the help of css.

- https://pr-1205-fossasia-susper.surge.sh

**Screenshots**

screenshot from 2018-11-03 14-39-40

### CODE REVIEW

**Comment by rajvaibhavdubey** [comment]
@simsausaurabh I am not able to get why the travis build is failing, Can you please help me out with it.
Below is an attatched screenshot of the error.

screenshot from 2018-11-03 18-25-38

**Comment by rajvaibhavdubey** [comment]
@simsausaurabh Yes it's working now.

**Comment by praveenojha33** [comment]
@rajvaibhavdubey Please provide a valid surge link.

**Comment by rajvaibhavdubey** [comment]
@simsausaurabh Changes have been done.
screenshot from 2018-11-06 02-50-34


ThankYou :smile:

**Comment by simsausaurabh** [comment]
Please squash your commits into one, then it will be good to be merged.

**Comment by rajvaibhavdubey** [comment]
@simsausaurabh Please review.
Thankyou :smile:

**Comment by mariobehling** [comment]
This should not have been merged. Our goal is to follow the market leaders, e.g. Google. Footer bar should be on the bottom of the page always, not on the bottom of the screen!

**Comment by simsausaurabh** [comment]
We'll revert the commit, there was mistake in understanding the issue with description.

**Comment by pythongiant** [comment]
already fixed https://github.com/fossasia/susper.com/pull/1265/ @mariobehling @simsausaurabh

**Pull request merged**
