### PR TITLE
New design of the about component

### LINKED ISSUE #1221: Change the layout of About and Contact pages.
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

The images of About and contact us pages occupy the whole page instead we could have 1/4th or half page image.
On About page the image occupies more than the full page we have to scroll 1 and a half pages to get to the actual information.

**Screenshots of the issue:**

screenshot from 2018-11-17 03-19-02

screenshot from 2018-11-17 03-19-18

**Are you working on this**
Yes

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
Fixes #1221

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Proposed Design of the about component

- https://pr-1232-fossasia-susper.surge.sh

- screenshot from 2018-11-20 15-45-48
- screenshot from 2018-11-20 15-45-57

### CODE REVIEW

**Comment by Ryan10145** [comment]
@rajvaibhavdubey Fix these spacing issues:
image

**Comment by rajvaibhavdubey** [comment]
@praveenojha33 Please review this.
ThankYou :smile:

**Comment by praveenojha33** [comment]
@rajvaibhavdubey I have requested a review from other devs to know whether this is required or not.
@AakashMallik @prabhupant

**Comment by prabhupant** [comment]
i think it looks good...gives it a more friendly feel :+1: @praveenojha33

**Comment by AakashMallik** [comment]
@praveenojha33 Sorry sir, I have been really busy with a few PRs. This change looks okay to me given that the old about us page was a massive image and a few text. One suggestion would be to use some other design to present those photos. Bigs tiles look a bit off. @rajvaibhavdubey

**Comment by praveenojha33** [comment]
@AakashMallik Please do not call me sir, everyone is equal here.

**Pull request merged**
