### PR TITLE
Changes title according to search

### LINKED ISSUE #1299: Title of the page should change according to the search
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

the title 'Susper' remains the same no matter what you search

**Expected behavior:**

the title should change according to the search. For eg - if we search 'elon musk' , the title should become 'elon musk - Susper'. This is also implemented in google search

**Will work on the issue:**
Yes, i'm working on this issue

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Fixes #1299  

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- I've added functionality to change title according to search

- https://pr-1319-fossasia-susper.surge.sh

screenshot from 2018-12-19 23-07-08

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 @simsausaurabh please review :)

**Comment by praveenojha33** [comment]
The link which you have provided will not work unless travis is fixed.

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 I think there is a PR open for travis issue. I'll wait till it gets merged. :smile:

**Comment by shreyanshdwivedi** [comment]
@simsausaurabh I'll open an issue and work on it :)

**Pull request merged**
