### PR TITLE
Add Heroku generated app.json

### LINKED ISSUE #231: Add Heroku deployment
For multiple live previews for multiple pull requests, setup Heroku deployment from Heroku dashboard. Add `app.json` file to configure susper repo with heroku.

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
Fixes #231 .

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@harshit98  yes harshit I have enabled the pipelines.

**Comment by harshit98** [comment]
@nikhilrayaprolu but how we will be going to deploy?

**Comment by mariobehling** [comment]
@nikhilrayaprolu Which issue is this related to? Please open an issue and follow best practices.

**Comment by harshit98** [comment]
#231

**Comment by nikhilrayaprolu** [comment]
@mariobehling done. Updated with the issue number.

**Comment by harshit98** [comment]
@nikhilrayaprolu it is showing `application error`

**Comment by nikhilrayaprolu** [comment]
@harshit98 @mariobehling successfully deployed. this can be merged now.

**Pull request merged**
