### PR TITLE
Fixes #683, Susper now responsive on large screens, cleans css

### LINKED ISSUE #683: On large resolution screens search bar disappears and design is distorted
Please test the site on large screens and ensure all page items appear as expected. See the bugs on large resolutions in the screenshot below, please.
screenshot from 2017-07-22 15-29-16

### PR DESCRIPTION
**Pull request by Marauderer97**
Addresses issue #683 

Changes: Susper results page now responsive at all widths 
In this PR 

- I checked mobile responsive-ness again after making changes for large screens, made minor corrections
- Removed a lot of bootstrap influence and wrote personalized css, this has helped make the page more responsive
- Made adjustments for large screens

Demo Link: [https://marauderer97.github.io/susper.com/](https://marauderer97.github.io/susper.com/
)
Screenshots for the change: 

image
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 Please check now

**Comment by harshit98** [comment]
@Marauderer97 Please align the related searches.

screenshot from 2017-07-27 12-12-06

**Comment by Marauderer97** [comment]
@harshit98 Done

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 please check the alignments on mobile devices 
image

**Comment by harshit98** [comment]
@Marauderer97 

Please update your link. I'm still not able to see proper alignments.

screenshot from 2017-07-29 07-59-57

**Comment by Marauderer97** [comment]
@nikhilrayaprolu What is wrong with small screens?
@harshit98 Sorry, merging with the parent branch overwrote the changes, fixed it now. Please check

**Comment by harshit98** [comment]
@nikhilrayaprolu Please review.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu All was never aligned with results, please check the current susper.com, after 767px, the tabs are centre aligned, not aligned with the results

**Comment by hpdang** [comment]
Footer not staying on bottom.

screenshot from 2017-07-31 13-12-45

**Comment by Marauderer97** [comment]
@nikhilrayaprolu @harshit98 I would like your advice on this issue
To solve the issues mentioned above, I can only think of the following:
1. I write @media tags for the screen, and keep changing the min width of the result container. It is currently at 84vh, it will have to be changed by 2 vh every 50px from 1300px height onwards. (This might be a messy way to do it). Please note that simply setting the min width to a percentage will not solve the issue, since it needs either pixel values, or viewport-height values
2. I write a function in Javascript that can detect the viewport height, and then set the correct dimensions in the ngOnInit() function. The only disadvantage of this method is if I change the viewport dimensions after Init, it will still carry on with the old dimensions. 
Note: I am trying to figure out what google does, and how its layout seems so naturally spaced even at large heights, even thought they use the same font-sizes and padding values(I double checked). 
Any suggestions from your side are welcome. If you think there is a better way to solve this issue, please advise me.

**Comment by mariobehling** [comment]
@Marauderer97 Please check out loklak.net. It is working there. Please learn from projects in the community, especially when they are using the same technology stack.

**Comment by Marauderer97** [comment]
@mariobehling loklak uses an enveloping container, trying to replicate the same

**Comment by Marauderer97** [comment]
I have realized that loklak has a lot of content by default per page, that is why the footer stays pushed to the bottom, in case of less content, they leave the same amount of empty space. I have followed the same format in Susper now. 
image
**I have made susper responsive until 1920px x 1920px**

**Comment by Marauderer97** [comment]
image
 
image

**Comment by Marauderer97** [comment]
@harshit98 @nikhilrayaprolu Please review now

**Comment by mariobehling** [comment]
@Marauderer97 Please make it easier for everyone and test your code more in detail.

**Comment by Marauderer97** [comment]
@mariobehling If you don't mind, can we please merge this PR as the first iteration which makes the screen responsive till 1920x1920px, I will work on a fresh PR to solve this issues beyond 1920px, the current PR being really old causes merge conflict problems with the repo and also causes trouble when I deploy in github using cherry-picking.

**Comment by Marauderer97** [comment]
@mariobehling Forgive me if my doubts sound stupid but:
1. Results appear in my screen
image
2. I have ensured that for small content on regular screens, there is no scroll required
image
3. As for implementing the same style as loklak, I am trying to replicate their design, and would prefer doing extremely large screens (greater than 1920 px) in a fresh PR to avoid the current PR getting messier

**Comment by mariobehling** [comment]
Please resolve conflicts. I changed the PR message to "Addresses issue...". You can finish this issue in another PR then.

**Comment by Marauderer97** [comment]
`ng-test` is failing on merging with master

**Pull request merged**
