### PR TITLE
Fixes #1066: Used a simple light box to display charts

### LINKED ISSUE #1066: Move charts to "more" as they provide little added value
The charts in the sidebar have little added value currently as the data they are based on is limited. Please implement a button "More Analytics" and show the charts on a lightbox display.

screenshot from 2018-07-01 15-32-24

### PR DESCRIPTION
**Pull request by praveenojha33**
Fixes #1066 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
Implemented a simple lightbox to display chart.
Surge Link: https://pr-1084-fossasia-susper.surge.sh
Screenshot:
image

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@praveenojha33 surge link is not valid. Please fix travis since it is not deployed.

**Comment by simsausaurabh** [comment]
@praveenojha33 It seems some abrupt. Please make the lightbox background of size equal to screen and secondly it should close on clicking outside the chart box in free region. Try to make something like twitter status lightbox?

**Comment by simsausaurabh** [comment]
@mariobehling Please provide your view about how it should be displayed.

**Comment by praveenojha33** [comment]
@simsausaurabh Please review I have made suggested changes.

**Comment by mariobehling** [comment]
Please reopen this as a PR to dev branch.

**Pull request closed without merging**
