### PR TITLE
Fixes #1310: Travis issue fixed

### LINKED ISSUE #1310: Fix Travis
Travis is currently not working. Please help to fix it.

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #1310 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- I have reused hidden instead of ngIf

- https://pr-1316-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by subhahu123** [comment]
what is ngif

**Comment by AakashMallik** [comment]
> what is ngif

@subhahu123 ?? Angular directive. Sorry I didn't get the context of this question. Was it something else you wanted to ask?

**Comment by subhahu123** [comment]
i have seen your changes but ended up with nothing (i don't know much about angular)
what was problem in travis cl and what have u done to fix .
just an overview

**Comment by AakashMallik** [comment]
> i have seen your changes but ended up with nothing (i don't know much about angular)
> what was problem in travis cl and what have u done to fix .
> just an overview
> @AakashMallik

It was caused because [hidden] just sets the display to 0 while ngIf removes the node completely. The tests check whether or not those nodes are available in the DOM tree. So, when ngIf was used, it was unable to find that node. That is why travis was failing.

**Pull request merged**
