### PR TITLE
Fix 1268 - Fix overlapping Help Section with footer

### LINKED ISSUE #1268: Removing Overlapping in Help  Section
**I'm submitting a ...**
- [x] bug report

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1268 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

- https://pr-1271-fossasia-susper.surge.sh

Earlier :
screenshot from 2018-12-07 10-17-32
Now :
screenshot from 2018-12-07 10-21-08

### CODE REVIEW

**Comment by sk9331657** [comment]
@fossasia/susper  Please review.

**Comment by rajvaibhavdubey** [comment]
@sk9331657 The footer has already been fixed in https://github.com/fossasia/susper.com/pull/1265 , You can view it in the surge preview link over there.

**Comment by sk9331657** [comment]
@fossasia/susper  Please review.

**Comment by sk9331657** [comment]
@praveenojha33  Conflicts resolved.

**Comment by sk9331657** [comment]
@praveenojha33  Can you review the pr as there are no conflicts showing up on my side??

**Pull request merged**
