### PR TITLE
Fixes #676 infinite scroll feature implemented for images

### LINKED ISSUE #676: Provide endless scrolling feature for images.
**Actual Behaviour**

Currently, the image section is having a pagination bar to view more images.

screenshot from 2017-07-21 07-45-49

**Expected Behaviour**

The image section should have endless scrolling feature similar to market leader. Pagination bar should not be present there to load more images.

Refer #147 and #634

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
#Fixes issue #676
Infinite scroll feature is implemented,

Demo Link: http://susper-pr-692.herokuapp.com/

Screenshots for the change: 
https://youtu.be/-mzlZt_NE8E

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@harshit98 resolved conflicts and merged recent changes.

**Comment by harshit98** [comment]
@nikhilrayaprolu Can you provide a screenshot of the following changes which have been done? The preview link seems to be throwing 404 error.

**Comment by nikhilrayaprolu** [comment]
@harshit98 
image
please try with the http link which is updated

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
