### PR TITLE
Removing extra angular package (animation)

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

-

- https://pr-1455-fossasia-susper.surge.sh

-

### CODE REVIEW

**Review by Pipe-Runner — COMMENTED** [review]
Fill up the PR template properly. Rest looks fine to me. IMO, we need to use Angular material instead of bootstrap. So we will need to reintroduce angular/animations later.

**Review by sakshee-19 — COMMENTED** [review]
Have you tested the project so that nothing breaks.

**Comment by subhahu123** [comment]
@sakshee-19  nothing break

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
@subhahu123 Can you please tell what is the need of making this change and how it is going to improve the project. Also please open a relevant issue stating the importance of this change.

**Review by simsausaurabh — COMMENTED** [review]
Please let it be there for now. Till then please work on some other high priority issues.

**Pull request closed without merging**
