### PR TITLE
Fixes #609: Improve auto correct UI

### LINKED ISSUE #609: Improving autocorrect UI
**Actual Behaviour**

screenshot from 2017-07-07 14-33-47

**Expected Behaviour**

It should follow market leader -
screenshot from 2017-07-07 14-33-40

I would like to work on this. :+1:

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #609 

Changes: 
- improved UI of autocorrect.

Demo Link: https://harshit98.github.io/susper.com/

Screenshots for the change: 

screenshot from 2017-07-07 17-14-36

Kindly review @nikhilrayaprolu @Marauderer97

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 what do you mean by out of place?

**Comment by harshit98** [comment]
@Marauderer97 Fixed the alignment. Updated preview link also.

screenshot from 2017-07-07 22-10-39

**Comment by harshit98** [comment]
Why didn't Travis passed this test? It passed the test earlier.

**Comment by harshit98** [comment]
Travis passed. Please review @nikhilrayaprolu @Marauderer97

**Comment by harshit98** [comment]
@mariobehling done! made it responsive now.
- There is PR already open on search bar responsiveness. @Marauderer97 is working on it. See PR: #626 
- I will open up a separate issue for making results feed responsive.
- Regarding responsiveness of tabs, I will request @Marauderer97 if she can work on it as it will require perfect alignment w.r.t search bar. See PR: #626 
- Updated preview link: https://harshit98.github.io/susper.com/

screenshot from 2017-07-10 03-38-34

screenshot from 2017-07-10 03-38-54

screenshot from 2017-07-10 03-39-08

screenshot from 2017-07-10 03-39-17

screenshot from 2017-07-10 03-39-27

**Pull request merged**
