### PR TITLE
Added HTML Linters.

### PR DESCRIPTION
**Pull request by harshit98**
Referring this PR with issue #2 
Reviews needed :)

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@harshit98 check travis is showing some errors.and secondly resolve all linting issues,

**Comment by harshit98** [comment]
@nikhilrayaprolu ok. Should I resolve linting issues in all .html files? (If any other file also please mention like .css)

**Comment by nikhilrayaprolu** [comment]
@resolve all issues raised by the linter.

**Comment by nikhilrayaprolu** [comment]
@harshit98 looks like travis didn't run for this pull , check it

**Comment by Abhi2424shek** [comment]
@harshit98 check your Travis dashboard of your fork and enable Travis pls.

**Comment by harshit98** [comment]
@Abhi2424shek don't know why Travis is not running. Followed the same procedure suggested by you!

**Comment by harshit98** [comment]
@Abhi2424shek why travis is failing? Please review.

**Pull request closed without merging**
