### PR TITLE
Added Target blank in footer(#1245)

### LINKED ISSUE #1245: Footer link should open in new tab
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Links open on the same page

**Expected behavior:**
Should open on new tab(target= "_blank")

**Screenshots of the issue:**

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #1245 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Footer links will now open in new tabs

- https://pr-1285-fossasia-susper.surge.sh

-

### CODE REVIEW

**Comment by rajvaibhavdubey** [comment]
> But I didnt change the links @prabhupant

Try including the link without https, might work

**Comment by saarthakchats** [comment]
@rajvaibhavdubey Even that's not there in the code

**Comment by simsausaurabh** [comment]
@saarthakchats Since we have made it similar to market leader Google, which also opens these links in the same tab. Hence it would be good as it is.

@praveenojha33 Please provide your views.

**Comment by shreyanshdwivedi** [comment]
I've fixed the links now :)

**Pull request closed without merging**
