### PR TITLE
Addresses #695: Meta tags for general purpose information

### LINKED ISSUE #695: Add meta tags for the general purpose information
Add additional meta tags for the general information on the browser and devices similar to loklak
https://github.com/fossasia/loklak_search/pull/457
https://github.com/fossasia/loklak_search/issues/455

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #695 

Changes:
- Add meta tags for general purpose information.

Demo Link: (Not applicable here)

Kindly review @nikhilrayaprolu @Marauderer97. Please suggest if anything more can done.

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 Have you ensured every img tag has the alt attribute?

**Comment by harshit98** [comment]
@Marauderer97 There are some alt attribute with name `alt="brand"`. Should I change it to `alt="susper"`?

**Comment by nikhilrayaprolu** [comment]
@harshit98 lets get this merged but since this is a pull with only half of the issue solved, change the title to adresses #695

**Comment by harshit98** [comment]
Done @nikhilrayaprolu

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
