### PR TITLE
Loading animation added to result component

### LINKED ISSUE #1173: Display Loader while search result is being fetched.
**I'm submitting a ...**
- [x] feature request

**Current behavior:**
There is not any loader or such kind of notification, which tells the user that website is running and there search result is in progress

**Expected behavior:**
A loader should be displayed to user end, which notifies that there search is being processed, also this increases User Experience.

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #1173

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] Added Surge preview link

#### Changes proposed in this pull request:
I have added the requested loading animation.

[pr-1204-fossasia-susper-temp.surge.sh](url)

ezgif-5-aed48771badb

### CODE REVIEW

**Comment by AakashMallik** [comment]
@praveenojha33 As I have added the loading animation, but seems like 4 of the unit tests are failing. I haven't removed any component but the tests can't seem to identify them. I am not sure how to fix this but the loading animation is working perfectly fine.
I have added a gif for the sake of originality but it can be replaced with just about anything.

**Comment by AakashMallik** [comment]
@praveenojha33 Sir, I have found the problem with the test case here. The **hidden** directive that was used earlier would hide the DOM element, but not remove it from the DOM tree, while **ng-if** not only hides it but completely removes it from the tree. Now as the loader would be shown until contents are loaded and none of the other components would be present in the DOM tree until then, hence those test cases are failing. I would say, the test cases were not written in order to work with ng-if in the first place. Let me know your views on this.

**Comment by praveenojha33** [comment]
@AakashMallik I think using ngIf might affect the performance as hiding and showing is fast as compared to loading all elements in DOM again. Also passing of travis is must, please try to achieve this with hidden attribute only, please search for the solution to handle the hidden DOM element that is causing the trouble in styling.

**Comment by AakashMallik** [comment]
> @AakashMallik I think using ngIf might affect the performance as hiding and showing is fast as compared to loading all elements in DOM again. Also passing of travis is must, please try to achieve this with hidden attribute only, please search for the solution to handle the hidden DOM element that is causing the trouble in styling.

@praveenojha33 Okay, I'll make it happen ASAP.

**Comment by praveenojha33** [comment]
@AakashMallik We want to make UI similar to Google, Google do not have a loader. But currently susper results are slow therefore loader seems a good option( also loklak search has a loader).Therefore it would be great if other devs can suggest their views on it.

**Comment by AakashMallik** [comment]
> @AakashMallik We want to make UI similar to Google, Google do not have a loader. But currently Susper results are slow therefore loader seems a good option( also loklak search has a loader).Therefore it would be great if other devs can suggest their views on it.

Ummm, but this issue was opened by someone else, I had just picked it up. As far as I remember, I had asked you if I may work on it. Anyway, I guess more discussion would be required on this. 
And yes the loading time is way too much and some kind of waiting animation would be needed. For example, amazon displays empty cards in place of items, that kind of approach could also work, but a loader would be the simplest way to address this problem.

**Comment by sk9331657** [comment]
@praveenojha33  I want to work on it.

**Pull request merged**
