### PR TITLE
Fixes #800: Dockerize susper.com

### LINKED ISSUE #800: Dockerize susper.com
**Actual Behaviour**

Please state here what is currently happening.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Screenshots of the issue**

Attach a screenshot of the issue here.

**Yes, I would like to work on this issue**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes issue #800 

This PR Dockerizes the susper.com project.
Also, Added Docker button on README.md

### CODE REVIEW

**Comment by harshit98** [comment]
@bhaveshAn It is the time to learn some of the best practices:
- There should be always 1 commit for 1 PR. 
- PR name should be `Fixes #(issue number): PR name`
- Commit name should follow the same as PR name.

**Comment by bhaveshAn** [comment]
@harshit98 please review again. Thanks !!

**Comment by bhaveshAn** [comment]
@harshit98 please check now !!

**Comment by nikhilrayaprolu** [comment]
@bhaveshAn resolve conflicts

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
