### PR TITLE
Enhancements in 'About this page' section.

### LINKED ISSUE #66: Blurred icons.
In about this page section- the icons seems to be blurred (not sharp, pixels are observed) . I would like to work on this.
Also rather than using pictures, we can use icons. It would be much better to have fast website.
selection_002

### PR DESCRIPTION
**Pull request by harshit98**
Fixes #66 
I don't know why old commits are coming here in this PR. Sorry for that! Here is the screenshot of the following fix I have done - 
screenshot from 2017-02-15 20-54-08

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@harshit98 base branch for your pull isn't the default(angular) branch, each time you create a new branch checkout to 'angular' branch and then create the branch.

**Comment by Marauderer97** [comment]
@harshit98 The icons look great! Good work! But one thing.. its not just the old commits, you have several commits in the new PR too, try avoiding that, by having just one commit per PR, or by using squash and merge. Also try formatting your commit this way Fixes #issue-num, <what the commit does>. Good luck!

**Comment by nikhilrayaprolu** [comment]
@harshit98 check your Travis dashboard of your fork and enable Travis .

**Comment by harshit98** [comment]
Closing this PR, I'll make a new one.

**Pull request closed without merging**
