### PR TITLE
code link at the footer is working

### LINKED ISSUE #1432: Code link not working
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
code link on the footer is not working.

**Expected behavior:**
code link on the footer should be working properly.

**Screenshots of the issue:**
code

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #1432

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- code link at the footer is working

- https://pr-1433-fossasia-susper.surge.sh

### CODE REVIEW

**Review by subhahu123 — CHANGES_REQUESTED** [review]
@samagragupta  code link is working fine
please consider surge links for testing not the susper.com
because master is not updated with dev branch

No need of this

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
It is working fine please check on susper-dev.herokuapp.com.

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
link fixing is fine. But what changes have you made in package-lock.json? and why?

**Comment by simsausaurabh** [comment]
@samagragupta what is the status on this ?

**Pull request closed without merging**
