### PR TITLE
Fixes #1267: Infobox share modal, styling fixes, redundancies removed

### LINKED ISSUE #1267: Removing redundant code from Share Modal in Infobox
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The code implementation makes use of redundant code. The naming conventions are not followed as well. The border-radius styling is incorrect as compared to material standards. The box is not vertically centered. 

**Expected behavior:**
The changes I propose are:
- [ ] Remove redundant code and make use of a more elegant approach.
- [ ] Fix naming for classes and functions.
- [ ] Fix border-radius to and icon size to match that of Google's
- [ ] Fix the position of the box.

**Screenshots of the issue:**
screenshot-localhost-4200-2018 12 07-00-37-34

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #1267 

#### Checklist 

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

The changes I have made are:
- [x] Remove redundant code and make use of a more elegant approach.
- [x] Fix naming for classes and functions.
- [x] Fix border-radius to and icon size to match that of Google's
- [x] Fix the position of the box.

- https://pr-1270-fossasia-susper.surge.sh

#### Screenshot of the change
screenshot-localhost-4200-2018 12 07-00-57-27

### CODE REVIEW

**Comment by pythongiant** [comment]
height's too long

**Comment by AakashMallik** [comment]
> height's too long

Made some space for sharing it on other platforms. But sure, I can reduce it. @pythongiant

**Comment by praveenojha33** [comment]
Please remove the unwanted space from bottom.

**Comment by AakashMallik** [comment]
screenshot-localhost-4200-2018 12 07-20-25-21

Made the required changes.

**Comment by pythongiant** [comment]
I can't see the changes on the preview link

**Comment by pythongiant** [comment]
image

**Comment by AakashMallik** [comment]
Works fine for me.

screenshot-pr-1270-fossasia-susper surge sh-2018 12 07-22-50-36
@pythongiant

**Comment by pythongiant** [comment]
> Works fine for me.
> 
> screenshot-pr-1270-fossasia-susper surge sh-2018 12 07-22-50-36
> @pythongiant

Yup It was my bad

**Pull request merged**
