### PR TITLE
Improve dropdown menu UI

### PR DESCRIPTION
**Pull request by jhlindgren**
Fixes issue #781

### CODE REVIEW

**Comment by harshit98** [comment]
Hi @jhlindgren. Please share before and after screenshot.

**Comment by ajayns** [comment]
@jhlindgren  Hey! Thanks for trying to solve this issue, but it's always better if you mention in the issue that you are assigning yourself this and then only start working on it and submitting PRs. Just a suggestion so multiple people won't be working on the same bug and waste time.

**Comment by harshit98** [comment]
@jhlindgren Any status of the PR?

**Comment by jhlindgren** [comment]
dropdown

**Comment by ajayns** [comment]
@jhlindgren It's looking great! @harshit98 Do check it out

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
