### PR TITLE
Removing unsed Css for increasing performance ( with little formatting )

### LINKED ISSUE #1448: Removing unused Css ( make leaned css )
**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Current behavior:**

currently web app contains various css which are unused ( have no used on website ) but increasing the loading time of web app leading to decreasing performance .

**Will work on the issue:**
yes

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1448 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- removing the extra and unused css.

- https://pr-1447-fossasia-susper.surge.sh

- web app is working absolutely fine . i have it fully each and every section ( in my concern ) 
- removing extra css is not affecting the website in any manner.
- increasing lighthouse performance

### CODE REVIEW

**Comment by subhahu123** [comment]
@mariobehling  @praveenojha33  please review

**Comment by subhahu123** [comment]
@rajvaibhavdubey @shreyanshdwivedi  please review this

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
@subhahu123 I do not know how it is working fine for you but I am getting a lot of glitches while running Susper. Currently I am unable to get results therefore I am unable to review it properly. @AakashMallik @shreyanshdwivedi Please review.
Here you can see that top right service box collides with right screen.
image

Also please see your changes in other browsers.

**Comment by subhahu123** [comment]
screenshot_2019-02-01-13-39-18-270_com ucmobile intl
Coming to top dropdown i will fix iit

**Comment by subhahu123** [comment]
@praveenojha33 can u please tell some more glitches 
I have tries this uc,chrome but i did not find any

**Comment by shreyanshdwivedi** [comment]
@subhahu123 at first go I only found the service box alignment an issue, I'll try to find out glitches, if any and let you know

**Comment by subhahu123** [comment]
@praveenojha33 please review

**Review by sakshee-19 — APPROVED** [review]

**Comment by subhahu123** [comment]
@simsausaurabh  please review

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
@subhahu123 
1. How did you ensure that nothing breaks or changes due to your changes?
2. When you make a search query, while the results are being fetched and spinner is shown, result page should not be scrollable.

@praveenojha33 Can you please confirm that while we make a search query, and go back to main page, some of the links at footer are highlighted?

**Comment by subhahu123** [comment]
> 2. When you make a search query, while the results are being fetched and spinner is shown, result page should not be scrollable.
> 


@simsausaurabh 
it's working fine .
please compare it with http://susper-dev.herokuapp.com/
i have checked both .
both r doing the same thing

**Comment by subhahu123** [comment]
> @praveenojha33 Can you please confirm that while we make a search query, and go back to main page, some of the links at footer are highlighted?
>

i think yes

**Comment by simsausaurabh** [comment]
@shreyanshdwivedi Lets keep this as a low priority for now. It might break something.

**Pull request closed without merging**
