### PR TITLE
Fixes #319 Search type buttons aligned with search-bar

### LINKED ISSUE #319: Search type buttons not aligned with searchbar
The `All`, `Images`, `Video` button container should be aligned with searchbar.

Current:
a

Expected:
b

### PR DESCRIPTION
**Pull request by harshit98**
Closes #319 

Preview link : <a href="https://harshit98.github.io/susper.com/">here</a>.

Things I have done in this PR : 
- Aligned the search menu buttons with search-bar.

### CODE REVIEW

**Comment by daminisatya** [comment]
@harshit98 can you provide a screenshot with the changes?

**Comment by harshit98** [comment]
@daminisatya 

screenshot from 2017-05-22 10-36-44

**Comment by daminisatya** [comment]
The results list and the nav bar are not aligned on the same line. Refer to this. 
image

This is what i see

image

**Comment by harshit98** [comment]
@daminisatya Updated preview link - <a href="https://harshit98.github.io/susper.com/">here</a>.

Screenshot - 

screenshot from 2017-05-22 11-07-47

**Comment by AnshulMalik** [comment]
Hmm, I think this is a temporary fix for the issue, doing Ctrl+ and Ctrl-, on different view ports, it still doesn't work.

I created this issue seeking for a permanent solution, which requires some efforts, analysing both search bar and buttons.

I'll try to add a patch if possible.

**Comment by daminisatya** [comment]
@AnshulMalik True, Then the effort needs to be put in to all the components present. Please track it as a separate issue on making everything responsive. Let this commit go in. Thank you

**Pull request merged**
