### PR TITLE
Fix #1465 Removing unused imports from services and component

### LINKED ISSUE #1465: Remove unused  imports from components and services
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Currently , In some components and services , there are some unusable imports which is not used anywhere in those files. we should remove them they are not useful .

**Will work on the issue:**
yes

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1465 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- https://pr-1472-fossasia-susper.surge.sh

- removing unused imports from .spec.ts file and  .ts file which are not used in those files but have been imported.

-  For example in below screenshot  file contains some imports By, component , input,output
which are not use in testing so , i m removing these imports

screenshot-github com-2019 03 23-15-19-02

### CODE REVIEW

**Comment by subhahu123** [comment]
@mariobehling  @praveenojha33 @simsausaurabh please review and merge this

**Review by praveenojha33 — COMMENTED** [review]
@subhahu123  Please write a proper PR description and issue. So that others can easily understand about the issue and in case of any problem it will be easier to detect.

**Comment by subhahu123** [comment]
> @subhahu123 Please write a proper PR description and issue. So that others can easily understand about the issue and in case of any problem it will be easier to detect.

@praveenojha33  changes are very small  and does not include anything , however i have tried to do proper pr description please check and `merge` this
this is copy of     https://github.com/fossasia/susper.com/pull/1457   which is closed now but got approval for the merging

**Review by praveenojha33 — APPROVED** [review]
Thank You, A proper PR message helps everyone else to know about the changes and is also helpful while tracing any bug.

**Comment by praveenojha33** [comment]
There are some issues with service box and color of visited links on susper-dev.herokuapp.com. I have already opened issues related to it. Can you please look into it.

**Comment by subhahu123** [comment]
> There are some issues with service box and color of visited links on susper-dev.herokuapp.com. I have already opened issues related to it. Can you please look into it.

sure!

**Review by simsausaurabh — APPROVED** [review]

**Pull request merged**
