### PR TITLE
Fixes #830 Minor bug: Links not working for terms and privacy routes

### LINKED ISSUE #830: Minor bug: Links not working for terms and privacy routes
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

1. Incorrect `Board of Directors: Phuc Hau Dang` in https://susper.com/contact
2. Link not provided `please visit our contact page. ` in last line of https://susper.com/terms
3.  Link not provided `please visit our contact page. ` https://susper.com/privacy
4. Incorrect Link provided to Blogs at index page it is going to https://blog.fossasia.org/ instead of https://blog.fossasia.org/tag/susper/

**Expected behavior:**

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #830 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

1. Incorrect Board of Directors: Phuc Hau Dang in https://susper.com/contact **changed to Hong Phuc Dang**
2. Link not provided please visit our contact page. in last line of https://susper.com/terms **made it working** 
3. Link not provided please visit our contact page. https://susper.com/privacy **made it working** 
4. Incorrect Link provided to Blogs at index page it is going to https://blog.fossasia.org/ instead of https://blog.fossasia.org/tag/susper/ **made it working** 

Fixed Links not working for terms and privacy routes

### CODE REVIEW

**Comment by bhaveshAn** [comment]
@harshit98 @nikhilrayaprolu Can you please review this PR.

**Comment by harshit98** [comment]
@bhaveshAn Kindly describe what changes you've done in this PR. It is very difficult to follow up. You should always describe changes after the fix and before the fix (original changes).

- I have observed you do not provide any description (in PRs as well as on issues).
- No deployment link as well.
- No screenshots.

Please provide all the details as requested.

**Comment by bhaveshAn** [comment]
@harshit98 Please go through https://github.com/fossasia/susper.com/issues/830#issue-276853916 and Let me know can you now figure out the issue.

**Comment by bhaveshAn** [comment]
@harshit98 Can you please merge this

**Pull request merged**
