### PR TITLE
Fixes #34 about page link updated

### LINKED ISSUE #34: Add "About" page
Clicking on About this page under the help icon gives a 404 error.
image

### PR DESCRIPTION
**Pull request by Marauderer97**

### CODE REVIEW

**Comment by Marauderer97** [comment]
@nikhilrayaprolu In susper-backbone, "About this page" links to the about page of yacysearch portal, in fact all the links under the help icon are related to yacysearch. Do all of them require to be updated?
image

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 in susper-backbone about page is linked to https://github.com/fossasia/susper-backbone/blob/gh-pages/yacysearch/about.html
which is implemented in super-backbone itself and specifies about susper functionality

**Comment by mariobehling** [comment]
The goal is not to copy the style of the susper backbone page.

This new site should follow a more modern design like google.com and loklak.net. Please help to implement that. Do not follow the old susper site. Thank you. 

Closing this therefore.

**Comment by mariobehling** [comment]
@Marauderer97 Just a hint regarding pull requests - please also stick to best practices here and provide a description in pull requests with a link to the issue it is solving and a screenshot and link to the test site as well. Cheers.

**Pull request closed without merging**
