### PR TITLE
Fixes #749: Pagination bar changed for small devices

### LINKED ISSUE #749: Google shows next page instead of pagination bar in mobile devices
image

google shows next page instead of pagination bar in mobile devices, where as we show a full pagination bar,implement next page similar to google on mobile devices.

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #749

Changes: 
- Pagination bar changed for smaller devices similar to market leader.

Demo Link: https://harshit98.github.io/susper.com/

Screenshots for the change: 

screenshot from 2017-08-18 00-27-31
screenshot from 2017-08-18 00-28-01

Please review @nikhilrayaprolu @Marauderer97 
There are some conflicts while deploying it. @nikhilrayaprolu kindly deploy this PR on heroku.

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 @nikhilrayaprolu Why am I unable to see any results?
image

**Comment by harshit98** [comment]
The same thing is happening on susper.com @Marauderer97 

screenshot from 2017-08-19 09-28-17

**Comment by harshit98** [comment]
@nikhilrayaprolu Please review.

**Comment by harshit98** [comment]
@nikhilrayaprolu ok. Working on it. :+1

**Comment by harshit98** [comment]
Done @nikhilrayaprolu 
Please review @Marauderer97 

Screenshot:

screenshot from 2017-08-28 21-21-41

Preview link: https://harshit98.github.io/susper.com/

**Comment by nikhilrayaprolu** [comment]
image

can you make as simple as in Google

**Comment by harshit98** [comment]
Done @nikhilrayaprolu 

screenshot from 2017-08-29 16-55-33

screenshot from 2017-08-29 16-56-18

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
