### PR TITLE
Fixes #507 Match the width and height of search box and related areas to market leader

### LINKED ISSUE #507: Match the width and height of search box of market leader and related areas
Please match the width, height and functionality of market leader. The developer console shows 632 x 49 including border. Please use the browser developer console to determine the required sizes.

Also ensure that following content areas match the search box.
screenshot from 2017-06-17 16-31-38

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #507 

Changes:
- Matched the dimensions of search bar to market leader.
- Did changes in infobox, tabs, results feed to adapt the changes w.r.t search bar.

Demo Link: https://harshit98.github.io/susper.com/

Screenshots for the change: 

screenshot from 2017-06-20 07-50-43

kindly review @Marauderer97 @nikhilrayaprolu

### CODE REVIEW

**Comment by harshit98** [comment]
@Marauderer97 

- Microphone icon is a png format file. On github pages, those occur as broken images like if you check about, contact and terms page : they will look same. See my commit also - as there are no changes to microphone. So nothing happened to microphone icon it is working fine.
- Regarding search bar view : I have solved it as per issue. Google changes dimensions of search bar, when a search is attempted. I have opened up #524 already. Kindly follow up there with some tests please. So that these issues won't rise up again and we can work on other features (as discussed on susper channel on gitter) The changes you suggested will be solved there for homepage. I have updated preview link. Kindly review. Let me know if any more further changes has to be done.

**Comment by harshit98** [comment]
done! @mariobehling 

Updated preview link : https://harshit98.github.io/susper.com/

screenshot from 2017-06-21 14-00-56

**Comment by mariobehling** [comment]
Not sure how the search bar can be exactly in the center (the center of the search bar in the center of the page).
screenshot from 2017-06-21 21-45-19

**Comment by harshit98** [comment]
@mariobehling I'll open up a separate PR for this as you have already opened up issue #536 

This issue is again raised because of recently merge of voice search feature. Addition of microphone icon has increased the width of search bar due to which alignment has been disturbed.

**Comment by mariobehling** [comment]
@harshit98 Ok, thanks.

**Pull request merged**
