### PR TITLE
Fixes #35 (part 1), implements images and updates styling

### LINKED ISSUE #35: Problems with the pagination bar
The pagination bar has the following two problems

1. The next and previous only update the pagination bar, not the entire page
2. Its functionality for images is unclear, as it tries to display images from the same page where documents were last viewed.
@mariobehling @nikhilrayaprolu  What do you suggest? How should images be displayed? Should there be paging for them at all? Google doesnot display images in pages, it displays all of them at once. Should we implement something like that?
If images and videos have the paging system too, then where should it start from, from page 1 or the page the user is currently viewing in say documents?

### PR DESCRIPTION
**Pull request by Marauderer97**
Adds styling to images, pagination, search buttons, and general layout.

### CODE REVIEW

**Comment by Marauderer97** [comment]
@mariobehling any  added suggestions/requirements for the styling of susper? :smile:

**Comment by Marauderer97** [comment]
@nikhilrayaprolu can you please check why travis is failing?

**Comment by niranjan94** [comment]
@Marauderer97 looks like there was a connection timeout when travis was trying to pull from GitHub. A build restart has fixed it.

**Comment by Marauderer97** [comment]
image
1.Clicking on previous and next updates the page numbers correctly now.
image
2.Added padding for images 
 @nikhilrayaprolu  Any more suggestions with regard to styling?

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Done. Also added code reformatting .

**Pull request merged**
