### PR TITLE
Fixes #750, drop down box for mobiles

### LINKED ISSUE #750: Design infobox for Mobile Phones
Currently at around 1100 px Susper hides its Infobox. We can change this by implementing a different version of the infobox for mobiles like Google does here:
image

Refer #743 
I am working on this :+1:

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #750 

Changes: Drop down box for mobiles of all screen sizes. Infobox displayed with a collapsible Analytics box

Demo Link: [https://marauderer97.github.io/susper.com](https://marauderer97.github.io/susper.com)

Screenshots for the change: 

image
image
image
@nikhilrayaprolu @harshit98 Please review

### CODE REVIEW

**Comment by Marauderer97** [comment]
@mariobehling @nikhilrayaprolu @harshit98 I was thinking of removing related searches from the infobox since it is present at the bottom anyway at least for mobile view. Shall I proceed?

**Comment by harshit98** [comment]
@Marauderer97 Yes, you can remove the related searches from the infobox since it is already present at the bottom of the page.

**Comment by Marauderer97** [comment]
@harshit98 done
image

**Comment by harshit98** [comment]
@Marauderer97 Can you enhance the "Show Analytics" button more towards material design?

**Comment by Marauderer97** [comment]
@harshit98 Can you please elaborate what material design means?

**Comment by Marauderer97** [comment]
@harshit98 
image
Please check if this is alright?

**Comment by harshit98** [comment]
@nikhilrayaprolu Please review.

**Pull request merged**
