### PR TITLE
Cursor should change into finger pointer when hovered over button

### LINKED ISSUE #1394: Cursor should change into finger pointer when hovered over button
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
When cursor is hovered over . `Start a new crawl job` button , it does not change.

**Expected behavior:**
Cursor should change into finger pointer when hovered over button

**Screenshots of the issue:**
GIF-
ezgif com-video-to-gif 1

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by neeraj3029**
Fixes #1394 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
Cursor changes into finger pointer when hovered over `Start new Crawl Job` button.

- https://pr-1395-fossasia-susper.surge.sh

- GIF

ezgif com-video-to-gif

### CODE REVIEW

**Review by shreyanshdwivedi — COMMENTED** [review]
LGTM :+1:

**Review by sakshee-19 — APPROVED** [review]
LGTM :+1:

**Review by rajvaibhavdubey — APPROVED** [review]
LGTM :+1:

**Review by praveenojha33 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
