### PR TITLE
Addresses #269 Theme for Susper

### PR DESCRIPTION
**Pull request by harshit98**
Addresses #269 

Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>.

Things I have done in this PR -
-  Provided the theme for Susper. We can start adding up themes for susper from this step. 

Go `Tools` -> `Customization` . It will open up a modal and can choose desired theme. I have not much worked on theme. It will just change color of title and description in the results section.

@nikhilrayaprolu @Marauderer97 Kindly review :)

### CODE REVIEW

**Comment by Marauderer97** [comment]
Travis is failing @harshit98 please check

**Comment by Marauderer97** [comment]
@harshit98 Please resolve conflicts.

**Comment by harshit98** [comment]
@Marauderer97 Working at both the issues. :+1:

**Comment by harshit98** [comment]
@Marauderer97 I'll open a new PR regarding this. There are a lot of conflicts occurring which is failing tests.

**Pull request closed without merging**
