### PR TITLE
Fixes #854: Parallellize the Travis CI build

### LINKED ISSUE #854: Parallelize the Travis CI bui;d
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Travis CI builds run on only one instance.

**Expected behavior:**
Multiple instances should be used to decrease the build time and accessiblity of the logs

**Screenshots of the issue:**
- Not valid

### PR DESCRIPTION
**Pull request by abishekvashok**
Fixes #854 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

Parallelizes the Travis CI build across multiple VM machine instances to
decrease build times and to increase the accessibility of the logs.

The instances are categorized as:
- Build and deploy: For building and deploying.
- Code test: For testing the code under the given unit tests and coverage data of codecov
- Code lint test: For testing the code for lint errors

Fixes #854

See the Travis CI logs for this PR as a demo.

### CODE REVIEW

**Comment by abishekvashok** [comment]
@ParthS007 done. Please review!

**Comment by abishekvashok** [comment]
@nikhilrayaprolu pls merge if feasable thanks

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by abishekvashok** [comment]
@mariobehling ive deleted my fork and now it's unchangeable for this pr. Can I open a new one pls?

**Comment by harshit98** [comment]
@abishekvashok Yes. Kindly open a new one and close this one.

**Pull request closed without merging**
