### PR TITLE
Fixes #625, Search bar and tabs position adjusted accordingly

### LINKED ISSUE #625: IMPORTANT: Mobile compatibility Search bar in mobile view blocks tabs
**Actual Behaviour**

The search bar in the mobile view is blocking the tabs
**Expected Behaviour**

Have a clean UI without blocking tabs

**Screenshots of the issue**

image
#524  and #584 can be referenced here

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #625 

Changes: search bar and tabs position adjusted accordingly for mobile version of the site

Demo Link: [https://marauderer97.github.io/susper.com/](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 

image
image
image
image
image

NOTE: There is a problem, notice the line in the .ts file, where the nav-group width is set inside ngInit, This is a bad practice since the width is then permanently set, so I wrote a function, to first check the document width, however this function only runs once when the page is initialized, so it can still cause problems.
@nikhilrayaprolu @harshit98 I would like suggestions on this.
My only options were either to add !important to the other widths to make it responsive, or remove that line setting width to 632px.

### CODE REVIEW

**Comment by harshit98** [comment]
@Marauderer97 If you're solving the issue then align the tabs too, so that search bar can be perfectly aligned w.r.t tabs without disturbing other alignments. : )

- I can also see you have made the search bar responsive, but it has not been center aligned according to screen size.
- regarding `document` method inside `ngOnInit()`, it is being used to change the dimensions of the search bar. See issue: #507

**Comment by Marauderer97** [comment]
@harshit98 I know that it is being used to change the size, but changing the size from a .ts file is  a bad practice, since the size cannot be over written now, unless I use !important, and in that case codacy will fail.

**Comment by Marauderer97** [comment]
I have found a way to fix this temporarily, making sure the changes requested in #507 stay intact
@harshit98 Please verify:
image
image

Secondly, I have copied the Search bar positions and sizes from loklak.net
This is how it looks now
image
image
image
image

**Comment by harshit98** [comment]
@Marauderer97 How did you adjusted search bar dimensions? Please mention it here, it looks good to me but if PR gets merged and the #507 issue again arises then that will be a problem.

**Comment by Marauderer97** [comment]
@harshit98 Working on the requested changes
Will open a seperate issue on aligning tabs too

**Comment by Marauderer97** [comment]
Can anyone tell me why travis is failing, ng test is passing on my local set up:
image

**Comment by Marauderer97** [comment]
@harshit98 Made all requested changes please check now:
image
image
And as for adjusting search bar sizes, I used the same technique as of you for now, but did it in index.ts instead of results.ts, so that I can make the search bar responsive in results component

**Pull request merged**
