### PR TITLE
Fixed Alignment of Search Bar in Error page

### LINKED ISSUE #1314: Improper Alignment in 404 error page
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Less Spacing on The Left

**Expected behavior:**
Should be in centre

**Screenshots of the issue:**
screenshot from 2018-12-19 02-09-02

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1314 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Added margin and changing position attribute value

- https://pr-1325-fossasia-susper.surge.sh

- #### Screenshot
screenshot from 2018-12-20 12-01-29

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@subhahu123 No, I haven't zoomed in, its reset to 100%.

**Comment by simsausaurabh** [comment]
@subhahu123 No I haven't zoomed in, its already reset to 100%. Let other dev check it, might be problem at my side.

**Comment by AakashMallik** [comment]
@simsausaurabh @praveenojha33 Why do we even have a 404 page? Can someone explain the use case of this component? If the search results are 0 then we show no results found. And if the internet is down, the browser will show its own "not found" pages. Am I missing something trivial here?

**Comment by praveenojha33** [comment]
@AakashMallik Actually it was designed so that all the url which are invalid will be directed to 404 page. This feature is similar to Google for e.g. google.co.in/ancxsalckjccnl redirects us to 404 page.

**Comment by AakashMallik** [comment]
@praveenojha33 Ohkay. with that out of the way, lemme see why the coverage has gone down.

**Comment by AakashMallik** [comment]
@rajvaibhavdubey @praveenojha33 @simsausaurabh 

Line **31 to 36** in intelligence.component.ts has an **if** branch and a **for** loop. The tests are not covering those. That is why coverage has decreased.

**Pull request closed without merging**
