### PR TITLE
Depth field in Crawl Job page only accepts numbers

### LINKED ISSUE #1366: Crawl Job page needs changes
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Currently the page depth fields accept all forms of inputs

**Expected behavior:**
They should be restricted to only number inputs.

**Screenshots of the issue:**

screenshot 2018-12-29 at 6 07 25 pm
screenshot 2018-12-29 at 6 07 48 pm

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by neeraj3029**
Fixes #1366 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
Fields that take ask for depth of search results, now take only number inputs which was earlier text.

- https://pr-1381-fossasia-susper.surge.sh

### CODE REVIEW

**Review by rajvaibhavdubey — APPROVED** [review]
LGTM :+1:

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
Currently this feature is under development and unless and until the backend is not ready, this feature will be worked upon when we will have backend ready.

**Review by shreyanshdwivedi — COMMENTED** [review]
Yeah I agree to @praveenojha33 
We can get this corrected once backend is ready!

**Review by praveenojha33 — APPROVED** [review]
There are simple changes so I am merging it.

**Pull request merged**
