### PR TITLE
Fixes #257 Match the position of Tools following the market leader

### LINKED ISSUE #257: Match the position of 'Tools' following the market leader
Susper - 
selection_032
Google -
selection_033

I'm working on this issue. :+1:

### PR DESCRIPTION
**Pull request by harshit98**
Resolves #257 

Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>.

Things I have done in this PR : 
- Corrected the position of `tools` following the market leader.

Screenshots : 

selection_038

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 In your demo link, the fix is only for a particular screen size. For specific screen sizes the page always looked similar to google 
With this PR you need to ensure this happens at every screen size. Look:

image

image

image

image

image

I would suggest don't be in a hurry, take your time to make the PR, after you have ensured it works at all sizes :smile:

**Comment by harshit98** [comment]
Okay @Marauderer97 , working on this. :+1:

**Comment by harshit98** [comment]
@Marauderer97 done! 

Updated Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>.

Screenshots : 
Upto `915px`
selection_012

Upto `757px`
selection_013

Upto `385px`
selection_014

**Comment by harshit98** [comment]
@Marauderer97  @nikhilrayaprolu Due to some recent merge of pulls, I'm not able to sqaush commits due to conflicts. This will not happen next time. However, issue has been fixed completely.

Updated - Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>

**Pull request merged**
