### PR TITLE
fixing port number to be printed on console and fixed a comment typo.

### LINKED ISSUE #1383: no statement printed on console(e.g port number)
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Console Does not print any statement that ensures the server has started.

**Expected behavior:**
Prints Port number on console

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by ambujraj**
Fixes #1383

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Added PORT Number to be printed on console on running the server.js

- https://pr-1386-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by ambujraj** [comment]
@AakashMallik @praveenojha33 @simsausaurabh please review :)

**Comment by ambujraj** [comment]
@AakashMallik @praveenojha33 @simsausaurabh. It's basically a minor improvement for helping developers. Please review it soon so that I can work on other PR.

**Review by shreyanshdwivedi — COMMENTED** [review]
@ambujraj please fix the errors mentioned in Coday Quality so that we can proceed with the review

**Review by rajvaibhavdubey — COMMENTED** [review]
Codacy is also giving error due to the console statement. I'm not sure whether it needs to added or not.

**Comment by ambujraj** [comment]
@shreyanshdwivedi @rajvaibhavdubey The error is due to printing to console so that it can handle debugging. But I don't think that any debug statement should be matching the text I have entered into console statement.

**Pull request closed without merging**
