### PR TITLE
Fixes #183 Add susper as standard search engine to Chrome

### LINKED ISSUE #183: Add feature "Make Standard Search Engine" to Front page
We already have a way to add susper as standard search engine to Firefox. Please implement the same for Chrome/Chromium.

screenshot from 2017-04-28 04-56-22

### PR DESCRIPTION
**Pull request by harshit98**
Fixes #183 

The feature **'add susper as standard search engine'** now works for both Firefox and Chrome/Chromium browser. Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>.

Screenshots : 

Chrome/Chromium browser -

screenshot from 2017-05-01 18-58-50

Firefox -

screenshot from 2017-05-01 18-57-51

### CODE REVIEW

**Comment by mariobehling** [comment]
Not working for me on Chromium Version 57.0.2987.98 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

**Comment by mariobehling** [comment]
Neither working on Google Chrome.

**Comment by harshit98** [comment]
@mariobehling Okay, I'll look into it, but it is working fine on my machine for both Chrome and Firefox.

**Comment by mariobehling** [comment]
Don't see the implemented feature anymore after last changes. No "add search engine" box.

**Comment by harshit98** [comment]
@isuruAb @nikhilrayaprolu Please check if it is working on your machine - <a href="https://harshit98.github.io/susper.com/">here</a>.

**Comment by nikhilrayaprolu** [comment]
@harshit98  any updates upon this? Have you stuck anywhere?

**Comment by harshit98** [comment]
@nikhilrayaprolu  No I'm not struck. The code works for me on Chrome and Firefox both. I have just recently, updated my fork due to which preview has been lost. Can you look into the code though? or should I open a new PR? Thank you!

**Comment by mariobehling** [comment]
@harshit98 Please resolve conflicts and provide a new preview link. Thanks.

**Pull request closed without merging**
