### PR TITLE
Partially Fixes #261 Align the rendered images following the market leader

### LINKED ISSUE #261: Align the rendered images under 'images section' following the market leader
Image search in susper - 

selection_036

Image search in Google - 

selection_037

### PR DESCRIPTION
**Pull request by harshit98**
Partially resolves #261 

Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>.

Things I have done in this PR : 
- Aligned the rendered images in a row similar to google.

**Problem I'm facing** - There are images, which are having small dimensions due to which, it creates a problem while aligning with other images to a same height similar to google. 

Screenshots : 

Before changes -

selection_040

After changes -
selection_019

### CODE REVIEW

**Comment by harshit98** [comment]
@nikhilrayaprolu ok. working on it. :+1:

**Comment by harshit98** [comment]
@nikhilrayaprolu  

Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>

Things I have done : 
- changed the `max-width` and `max-height` to simply `width` and `height` 

Changes observed : 
- This is how it looks now - 
selection_022
- One more thing I have observed after fixing this issue there are many other images also which are being loaded and because of this, in some different query search I have found `gif` format files are also being rendered with the images which should not be happening. I'll open up a separate issue for it.  
- This completely solves the issue of alignment of images. I have found some more bugs, which I'll be opening them as a separate issue.

**Comment by nikhilrayaprolu** [comment]
initially in susper we had all images of same size but later we changed it match the original size ratios to make it similar to what google does. Its something like just reverting back changes we made before.please look through it.
this is leading to some images with low quality being shown large.
image
some images getting distorted in shape.
see how google implements this.
image

**Comment by harshit98** [comment]
@nikhilrayaprolu This was the only solution. For most of the image search, it is working fine. Regarding, resolution of images and aspect ratio I'll open up a separate issue. There we can discuss what we can do. :+1:

**Comment by nikhilrayaprolu** [comment]
you are just repeating the history look at this line https://github.com/harshit98/susper.com/commit/ddcd616979a5ea1c8d10ee92198e1d6f91db70c9#diff-d236a4fac2ea257fbc23c7e908f0111eR46

**Comment by mariobehling** [comment]
Ok, so you are changing the ratio of images, which is not the expected view.

Suggestion in a first step scale the images to a common height, but do not change the ratio.

**Comment by mariobehling** [comment]
I also see you are continuously starting to work on new issues, while previous PRs are still open. You are potentially blocking others from working on issues as you already claimed issues.

**Comment by harshit98** [comment]
@mariobehling ok, I'll keep that in mind. I'll first solve the remaining open PRs. Regarding, your suggestion on images, I'll follow it. I'll try to scale the image to a common height without changing their ratio. :+1:

**Comment by harshit98** [comment]
There were some merge conflicts while rebasing. I'll open up a new PR.

**Pull request closed without merging**
