### PR TITLE
Changed shape of search-bar to curve shape

### LINKED ISSUE #1449: Change in search bar
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
susper search bar is in rectangle form,   I want to change its minor UI for a better experience

**Expected behavior:**

it can be changed sharp corner to the curved shape like google.

**Screenshots of the issue:**

google
**Will work on the issue:**
yes ofcourse

### PR DESCRIPTION
**Pull request by div12gau**
Fixes #1449 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Changed the shape of search-bar to curve shape

- https://pr-1462-fossasia-susper.surge.sh

-  image

### CODE REVIEW

**Review by praveenojha33 — COMMENTED** [review]
Please look at the corner of the search box.
image

**Review by praveenojha33 — APPROVED** [review]
LGTM :+1:  
However I think we should decrease the size of search box when it is scrolled on result page.
Please do it in this PR or open an issue for it.
image
Thank You !!

**Comment by praveenojha33** [comment]
@shreyanshdwivedi @AakashMallik Please review.

**Review by bhaveshAn — APPROVED** [review]

**Review by Pipe-Runner — APPROVED** [review]
Looks fine to me.

**Review by neeraj3029 — APPROVED** [review]
LGTM

**Pull request merged**
