### PR TITLE
Fix: Correct positioning of Susper logo in navbar

### PR DESCRIPTION
**Pull request by ajayns**
Addresses Issue #524 #729

Changes: Margin of navbar-logo was changed individually so as to vertically center it.

Screenshots:
Before
image

After
image

### CODE REVIEW

**Comment by harshit98** [comment]
@ajayns Please share screenshots of mobile responsiveness as well.

**Comment by ajayns** [comment]
@harshit98 Will do! Give me a day as I am travelling. Also, I would also you like you consider issue #779 
Cause then, I can make an entirely new component with common styling that is responsive and reused for all these pages. But if we are moving on with the current structure, I'll make the changes individually and also post screenshots. 

By the way, I'm pretty new to the travis-ci system so can you like give insights on why the build is failing, links, articles, anything would help! Thanks for the reply!

**Comment by harshit98** [comment]
@ajayns What's the status of this PR ?

Please update your branch so that travis build should pass. :)

**Comment by ajayns** [comment]
@harshit98 I will update with build passing. Give me a few mins

**Comment by ajayns** [comment]
@harshit98  Mobile responsiveness screenshots:
image
image

**Comment by harshit98** [comment]
@ajayns Your screenshots are different for the mobile responsiveness. Show responsiveness of `About us` page. Also, I have observed some unindented code. Please indent the code `.navbar-brand`. I will approve the PR after comparison. :)

**Comment by ajayns** [comment]
@harshit98 I'm really sorry about, I should've cross checked before committing. Won't happen in future. I've reindented the code and I'm attaching the screenshots for each page here.
screen shot 2017-10-05 at 08 18 54
screen shot 2017-10-05 at 08 18 58
screen shot 2017-10-05 at 08 19 02

**Comment by harshit98** [comment]
@ajayns Good work!
But I told you to indent CSS lines under `.navbar-brand`, not the whole file :)
Please fix it. Re-do the changes and indent only those lines under `navbar-brand` class.

**Comment by ajayns** [comment]
@harshit98
Hey! I will do the changes, but isn't it a good thing now that the whole file is reindented?

**Comment by ajayns** [comment]
@mariobehling @harshit98 Thanks! Please review merge the PR!

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
