### PR TITLE
connect contact button with contact page and fine tune

### LINKED ISSUE #174: Connect contact buttons to contact page
connect contact button to contact page

If we can open github and blog pages in new tab it will be helpful for keep our users in susper

### PR DESCRIPTION
**Pull request by isuruAb**
now external links are open in new tab.
contact button is connect with contact page

this fixes #174

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide test page on your own Github setup.

**Comment by isuruAb** [comment]
@mariobehling  why we need to open external links in same tab. if we can open them in new tab, we can keep user with us ??

**Comment by mariobehling** [comment]
These are project links. They are not external to the project.

**Comment by mariobehling** [comment]
We should also follow common ways across projects and simply follow market leaders. I am not up for discussing each single link in each project. Let's keep it simple for the moment and solve the urgent issues. We can progress much faster if all devs start to follow best practices more closely and we avoid mini-issues and get real stuff done.

**Comment by isuruAb** [comment]
@mariobehling  made those changes 👍

**Pull request merged**
