### PR TITLE
Fixes #144 Created a bottom bar in gray same as loklak.net

### LINKED ISSUE #144: Create a bottom bar in gray same as loklak.net
Example bar of loklak.net
screenshot from 2017-03-30 20-19-04

Left side links:
* About -> `/about`
* Blog -> `blog.fossasia.org`
* Code -> `https://github.com/fossasia/susper.com`

Right side links
* Terms -> `/terms`
* Contact -> /`contact`

### PR DESCRIPTION
**Pull request by harshit98**
Screenshot - 

selection_026

### CODE REVIEW

**Comment by mariobehling** [comment]
@harshit98 Thank you. Let's start to follow best practices similar to other projects here as well. Could you provide a link to a test page from your repo, please?

**Comment by harshit98** [comment]
@mariobehling I didn't got it, what you said. :sweat_smile: Do you mean by the preview link?

**Comment by nikhilrayaprolu** [comment]
@harshit98 you can host your site on your github-pages, and give us a link to it, so that we could review it on a live angular application you hosted.

**Comment by harshit98** [comment]
@nikhilrayaprolu Gone through the docs of susper, it is not able to deploy angular branch to gh-pages.

**Comment by nikhilrayaprolu** [comment]
@harshit98  do manual build everytime. I would instruct you to follow below steps:-
first from angular branch
```
git checkout -b master 
ng build
mv susper.xml dist/
mv dist/* .
git add .
git commit -m "commit messages"
git push origin master
```
why not gh-pages??
gh-pages is already hosted on susper.com on FOSSASIA repo, so it is better not to change the gh-pages branch, since it has some configurations required for hosting on this repo.
make sure that you choose master branch in github setting for hositng on gh-pages.

**Comment by mariobehling** [comment]
Ok, so I am merging to keep the flow of the contributions. Please ensure to add links for a test page in future. Thank you.

**Pull request merged**
