### PR TITLE
Fixing the terms and privacy (container alignment)(for small screen)(indentation)

### LINKED ISSUE #1466: Bug in terms and privacy component html and css  ( for small screens)
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

there is no margin for left and right in terms and privacy section ( for small screens like mobile)
**Will work on the issue:**
yes

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1466 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

-

- https://pr-1453-fossasia-susper.surge.sh

### Before
screen shot 2019-02-03 at 13 16 11
screen shot 2019-02-03 at 13 18 26
### After
screen shot 2019-02-03 at 13 30 48
screen shot 2019-02-03 at 13 30 56

### CODE REVIEW

**Comment by subhahu123** [comment]
@praveenojha33  @shreyanshdwivedi @rajvaibhavdubey @AakashMallik  please review this

**Comment by subhahu123** [comment]
@shreyanshdwivedi  please help why travis is showing error for closing tag </p>
saying that it is already closed .....

**Review by Pipe-Runner — COMMENTED** [review]
Changes look good to me. But CI is failing. Resolve that.

**Review by sakshee-19 — COMMENTED** [review]
Fix the CI.

**Comment by subhahu123** [comment]
@praveenojha33 please review

**Review by sakshee-19 — COMMENTED** [review]
Unable to see the snapshots. Could you please update your PR description.

**Comment by subhahu123** [comment]
> Unable to see the snapshots. Could you please update your PR description.

@sakshee-19  please open them (by click)
images was big so i have changed their link to comment section  
they are viewable ............

**Review by praveenojha33 — COMMENTED** [review]
Please open an issue and reference this PR.

**Comment by subhahu123** [comment]
> Please open an issue and reference this PR.

@praveenojha33  done

**Comment by praveenojha33** [comment]
Please rebase.

**Comment by simsausaurabh** [comment]
@subhahu123 It makes very difficult for us to review PRs with no proper description, un-squashed commits, could you create a separate PR and fix everything. I am closing this one for now.

**Pull request closed without merging**
