### PR TITLE
Made footer responsive for small screen size-320px

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #713 

Changes: Footer navbar is now responsive for all the screen sizes. 
- Small - 320px
- Medium - 375px
- Large - 425px

Demo Link: https://harshit98.github.io/susper.com/

Please review @nikhilrayaprolu @Marauderer97

### CODE REVIEW

**Comment by harshit98** [comment]
screenshot from 2017-08-06 11-54-56
screenshot from 2017-08-06 11-55-16

Try the preview link on your phone. It is working well. Use chrome responsiveness feature. It gives the best idea about responsiveness.

**Comment by Marauderer97** [comment]
Still happening at sizes slightly greater than 320px. (At 340px)
image

**Comment by harshit98** [comment]
Okay, @Marauderer97 working on it. :+1:

**Comment by harshit98** [comment]
@Marauderer97 done.
screenshot from 2017-08-07 21-19-21

**Comment by Marauderer97** [comment]
@harshit98
image

**Comment by Marauderer97** [comment]
@harshit98 I am insisting on center-align to avoid this
image

**Comment by harshit98** [comment]
@Marauderer97 Done!

screenshot from 2017-08-08 20-38-38

screenshot from 2017-08-08 20-38-52

**Comment by Marauderer97** [comment]
image
is your preview link updated?

**Comment by harshit98** [comment]
updated @Marauderer97

**Comment by nikhilrayaprolu** [comment]
@harshit98 good work.
please decrease the padding between the upper row and the lower row in footer, as it also overlaps with cancel button.

**Comment by harshit98** [comment]
@nikhilrayaprolu Smaller screen size starts from 320px. The issue which you're telling is below 320px. There is no need. : )

**Pull request merged**
