### PR TITLE
Parent #797:Removed Infobox that used DBpedia API

### PR DESCRIPTION
**Pull request by praveenojha33**
Parent #797 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
**Parent #797:Removed Infobox that used DBpedia API** :
DBpedia API was not available on `https` . Feature like `Related Search` and `Infobox` was implemented using DBpedia API. These features was getting blocked on susper.com and was a reason for instability due to Mixed Content Problem.

Surge link: https://pr-1008-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by praveenojha33** [comment]
@simsausaurabh Actually YaCy server is down.
Even susper.com is not showing results check it out.

**Comment by praveenojha33** [comment]
@mariobehling Please review

**Comment by mariobehling** [comment]
Please resolve conflicts. Thanks.

**Comment by praveenojha33** [comment]
@mariobehling Merge conflicts have been resolved please review.

**Pull request merged**
