### PR TITLE
Fixed #879: Added a sister project

### LINKED ISSUE #879: Add more sister projects
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

less projects
**Expected behavior:**

more added
**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by samyakbvs**
ADDED PSlab

### CODE REVIEW

**Comment by harshit98** [comment]
@samyakbvs Go through readme file and please provide here deployment link.

**Comment by samyakbvs** [comment]
https://pr-884-fossasia-susper.surge.sh/

**Comment by samyakbvs** [comment]
Pls merge without squashing

**Comment by samyakbvs** [comment]
After merging it will show up as it wasn't showing up when I made the preview link

**Comment by samyakbvs** [comment]
But then I made the required changes but the preview link doesn't get updated with commits

**Comment by naveentherocker** [comment]
@samyakbvs That is not the real problem. Check your Code. You have entered the name of the Image incorrectly.

**Comment by samyakbvs** [comment]
Thank you @naveentherocker I was having a misconception

**Comment by naveentherocker** [comment]
@samyakbvs Why are you saying that `Merge without Squashing?`

**Comment by samyakbvs** [comment]
Bcs there is some problem I can only squash consecutive commits

**Comment by samyakbvs** [comment]
@nikhilrayaprolu pls merge

**Pull request merged**
