### PR TITLE
(#1261)Style Fixes in Privacy Page

### LINKED ISSUE #1261: Problems in the Privacy page
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
- Incorrect CSS makes text look like a link unnecessarily
- Hidden text - text and link not visible, footer is covering it
- Wrong class -- issues with CSS

**Expected behavior:**
- Fix CSS
- Add padding and margin
- Make all required things visible

**Screenshots of the issue:**
## This text is incorrectly styled
screenshot 2018-12-06 at 3 42 12 pm

## Hidden text in the contact section
screenshot 2018-12-06 at 3 42 20 pm

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #1261 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

-

- https://pr-1260-fossasia-susper.surge.sh

-

## Before
screenshot 2018-12-05 at 2 29 47 pm
^^^ There is text behind that footer ^^^
screenshot 2018-12-05 at 2 31 17 pm
^^^ Unnecessarily looks like a link --> misleading ^^^
## After
screenshot 2018-12-05 at 2 56 29 pm

### CODE REVIEW

**Comment by saarthakchats** [comment]
Waiting for the preview myself 😅

**Comment by pythongiant** [comment]
open an issue too
use ng serve to check your changes

**Comment by saarthakchats** [comment]
@praveenojha33 Done

**Comment by praveenojha33** [comment]
@saarthakchats Please update your issue and make it relevant and detailed.

**Comment by saarthakchats** [comment]
Don3 @praveenojha33

**Comment by AakashMallik** [comment]
screenshot-pr-1260-fossasia-susper surge sh-2018 12 07-22-37-48
screenshot-pr-1260-fossasia-susper surge sh-2018 12 07-22-37-40

It seems that the fix you did simply removed the underline, which is good to begin with, but I think you should change the stying of the text to make it look like a heading. Also, make the same changes in **terms** as well as changing styles only in a single place would make it look inconsistent. 

Good luck @saarthakchats

**Comment by saarthakchats** [comment]
all done @AakashMallik

**Pull request merged**
