### PR TITLE
Fixes #254 Pagination bar of images not working

### LINKED ISSUE #254: Pagination bar of images not working on refresh
Pagination bar in images not working as expected.
Here the pagination bar for images shows 10 pages,
image

Clicking on any page (say the third), takes the site to all documents, and does not display images any more
image

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
In reference to issue #254 
Now that when user refreshes the image page, the images are displayed on page change.
Demo link: https://nikhilrayaprolu.github.io/susper.com-1/

### CODE REVIEW

**Comment by Marauderer97** [comment]
@nikhilrayaprolu I am not able to refresh the image results and check. It shows me an error, can you deploy to your github pages too, those links seem to allow refresh

**Comment by nikhilrayaprolu** [comment]
Demo link is on gh-pages

**Comment by Marauderer97** [comment]
@nikhilrayaprolu This is what I see when I refresh
image
image
Please check.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 do you mean about the page number?

**Comment by mariobehling** [comment]
Still buggy, but an improvement. Let's iterate. I am merging this as work in progress. Thanks.

**Pull request merged**
