### PR TITLE
Fixes #1016 #1014 and #1013:Fixed UI of Infobox and Analytics box and made it responsive for all screen sizes.

### LINKED ISSUE #1016: Improve UI of Analytics Box and Infobox.
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently the Analytics Box is not visible as results are not retrieved from YaCy. Infobox has been implemented without having a check on Analytics Box which is also a part of Infobox in SUSPER. 
There are currently UI issues like responsiveness and alignment of both Infobox and Analytics box.

**Expected behavior:**
Improve UI of Analytics Box and Infobox

**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by praveenojha33**
… 

Fixes #1016 #1014 #1013 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
Results are now appearing on susper.com and there is a lot problem in alignment of components such as Statsbox(Analytics box) and Infobox. This PR will fix all UI issues. Sometimes the result might not be visible therefore I have attached a GIF.

- Surge Link: https://pr-1017-fossasia-susper.surge.sh

- out

### CODE REVIEW

**Comment by praveenojha33** [comment]
@simsausaurabh For some screen sizes it is not possible to display infobox as normal. For Screen sizes of width between 1131px and 768px infobox will be hidden. For all other screens it will be visible properly. Please review and if there is any problem with screen sizes above 1131px. Please mention.

**Comment by simsausaurabh** [comment]
@praveenojha33 Is that normal that I am getting huge gap above the info-box?

screenshot from 2018-06-05 09-37-46

For screen size like this, the info-box and intelligence box should be aligned vertically too. And whether results are coming or not, the intelligence box should come at the top.

screenshot from 2018-06-05 09-39-32

**Comment by praveenojha33** [comment]
Hello @simsausaurabh When the results will come then there will be no extra space above the intelligence box. Position of Infobox is another open issue and it requires results to appear, I will fix that soon.

**Comment by praveenojha33** [comment]
Hello @simsausaurabh Please e this, we all know that current UI of susper gets disturbed when results are displayed. Also I have implemented image section infobox

**Comment by simsausaurabh** [comment]
@hemantjadon please review and provide your suggestions.

**Comment by simsausaurabh** [comment]
@praveenojha33 

I am not getting info-box in window width range from 768 to 1131. For some width < 768, the ```Show Analytics``` button and infobox is not aligning with intelligent section.  Please fix it. Also fix the alignment of 9-dot icon. Please see the screenshots below.

screenshot from 2018-06-06 18-41-20

screenshot from 2018-06-06 18-45-03

**Comment by praveenojha33** [comment]
Hello @simsausaurabh  for showing infobox between 1131px and 767px I have opened an issue here #1020 .Also  Show Analytics button is at right place, if you will notice carefully the intelligence section is dis aligned (the left margin is somewhat more), and currently there is an issue regarding position of intelligence section as well #1009 . I will fix #1009 once this PR is merged and also I will go through issue #1020 and find an appropriate solution for it.

**Comment by simsausaurabh** [comment]
@praveenojha33 What about these two issues?

1. The ```Show Analytics``` button is not aligned.

screenshot from 2018-06-06 23-53-45

2. The 9-dot menu icon is not aligned.

screenshot from 2018-06-06 23-54-03

There are no other issues opened for these. Could you please try to fix small issues in a single patch, rather than opening an issue for each small CSS issue?

**Comment by praveenojha33** [comment]
@simsausaurabh I will work on responsiveness, once we finish priorities.

**Comment by praveenojha33** [comment]
@mariobehling Please review.

**Pull request merged**
