### PR TITLE
Adding hover effect for the search bar

### PR DESCRIPTION
**Pull request by akalanka95**
#### Checklist

- [x]  I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Changes were made to the search bar component css file. Add the hover effect to the search bar when the user's mouse pointer is in the search bar.

- src/app/about/search-bar.component.css

#### Preview link:
- https://pr-949-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by praveenojha33** [comment]
Please add a bit more description about your PR,add screenshots highlighting your change else everything LGTM . Good Work :+1:

**Comment by praveenojha33** [comment]
Though you have checked 'I have read the Contribution & Best practices Guide and my PR follows them' but actually it is not.Please associate your PR with an issue.It is the first line in Commits/PR section in [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/#commits)

**Comment by vaibhavsingh97** [comment]
@duttaditya18 Please check PR carefully before approving. Carefully I mean functionality after merging the PR should be intact, no code comment should be there, etc.
@praveenojha33 It's just a CSS change, it can't effect functionality

**Comment by praveenojha33** [comment]
@vaibhavsingh97 The effect must be visible on susper.com .Further the theme implemented by @ValentinBercaru and changes proposed in few other PRs are not working. Please have a look.

**Comment by ValentinBercaru** [comment]
Yes, I try to find out where's the problem with the theme.

**Pull request merged**
