### PR TITLE
Addresses #608 #633 #524 #584 Makes search bar and drop-down responsive, cleans css

### PR DESCRIPTION
**Pull request by Marauderer97**
Addresses #608 #633 #524 #584 

Changes:The following changes have been made:
On an external level:
- Fixes search bar position and dropdown position in index page

In terms of design
- There were a lot of css errors in the search bar and drop-down alignments, search bar and dropdown css alignments were rectified, to be more scalable, eg. float instead of exact pixel values, vw instead of percentages
- Now on inserting these components anywhere, there will be no pre-defined css, it will only come with minimal css, and you can position it wherever you want
- No more problems like, fixing index page css disturbs results page css, and vice versa
- I seperated the css and re wrote the css for resuts page, index page , and individual components to prevent all such problems
- Rewrote css without spoiling current arrangement for search bar, suggestion box, navbar and drop-down boxes
 Please note to follow a similar style with all new components added, to prevent this problem in the future

Demo Link: [https://marauderer97.github.io/susper.com](https://marauderer97.github.io/susper.com)

Screenshots for the change: 

A few examples, please check the demo link though:
image
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 @nikhilrayaprolu I was forced to use `!importan`t in one place since we need the search bar to be of length 584 and 632 px initially, but after a width of 767px, we need to change the length of these search bars forcefully

**Comment by Marauderer97** [comment]
@harshit98 lint issues are not from this PR, they are from a recently merged PR, failing every PR made, as for the dropdown, it is being hidden on the results page, that is why I let it stay hidden on the index page, following market leader, just like you did for the results component. However, let me try to come up with a better solution for small screen sizes on both index and results page, because the drop down should be ideally accessible on any page irrespective of the screen size

**Comment by Marauderer97** [comment]
@harshit98 Made requested changes please check now

**Comment by harshit98** [comment]
@Marauderer97 Seems to be good now but when I open drop-down, the drop-down is not getting displayed.

**Comment by Marauderer97** [comment]
@harshit98 That is because the dropdown is not responsive, this is how it appears for width less than 767px, initially the dropdown designed turned into a hamburger icon below 767px width, it was collapsable, when you renovated the drop down menu, you left those classes but didnot make it collapsible, that is why these errors. The entire menu css might have to be changed

**Comment by Marauderer97** [comment]
@harshit98 @nikhilrayaprolu With the current css classes used in the dropdown, this is the best fix.
Is this alright?
image
If not, we will have to write the css for the entire dropdown again(it uses prefdefined bootstrap classes such as col-sm-4 causing the problem

**Comment by mariobehling** [comment]
> If not, we will have to write the css for the entire dropdown again(it uses prefdefined bootstrap classes such as col-sm-4 causing the problem

Please open an issue for this. We need something that works better.

**Comment by Marauderer97** [comment]
@mariobehling Alright, I will treat making a responsive menu for the drop down as a seprarate issue. I will open an issue on it, and in this case this PR is now complete

**Pull request merged**
