### PR TITLE
Addresses #121 Autocomplete feature

### PR DESCRIPTION
**Pull request by harshit98**
Addresses #121 Implementation of autocomplete feature for susper.

Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>

Things I have done in this PR :
- Created a action for autocomplete in `src/app/actions/suggest.ts`
- Created effect for autocomplete in `src/app/effects/suggest-effects.ts`
- Created reducers by name `suggest.ts`
- Created a `suggest-service`

Problems I'm facing : 
- After implementing the actions, reducers and effects I'm not able to figure out how should I proceed further. Previously, I implemented the code in search bar component due to which, the code gets blocked.

@nikhilrayaprolu @Marauderer97 Can we merge this as first step for autocomplete? Please review and it would be great if you can give your suggestions for how should I proceed further.

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 Travis is failing, Please check.

**Comment by mariobehling** [comment]
@harshit98 In howfar is this a first step? I don't see anything getting solved. Please refine your solution or break it down in smaller issues.

**Comment by AnshulMalik** [comment]
@harshit98 Can you please update the preview link, it appears to be broken.

**Comment by harshit98** [comment]
@AnshulMalik Link is already updated! It's not broken.

**Comment by AnshulMalik** [comment]
Ah, I see, this was the problem with mixed content, chrome was not loading http content over https.

**Comment by nikhilrayaprolu** [comment]
I think we aren't running susper on https, so that isn't the problem

**Comment by AnshulMalik** [comment]
We are calling the the `http://yacy.searchlab.eu` over http, so this is the mixed content. Looks like you didn't know.
sra

**Comment by nikhilrayaprolu** [comment]
@AnshulMalik how is http over http is mixed content?
first know that http on https is mixed but not http on http

**Comment by AnshulMalik** [comment]
Argh, That's what I was saying, we are callling http://yacy.searchlab.eu not https://yacy.searchlab.eu.

**Comment by nikhilrayaprolu** [comment]
susper is on http and yacy is on http, yacy doesn't have a https port. Looks like you didn't know

**Comment by AnshulMalik** [comment]
Yeah, I didn't know yacy doesn't support https. Thanks for updating me :)

**Comment by nikhilrayaprolu** [comment]
and tell me how did you call http over http as mixed? How did you guess that calling the http has raised the problem?

**Comment by AnshulMalik** [comment]
Chrome screamed

> Mixed Content: The page at 'https://harshit98.github.io/susper.com/search?query=&verify=false&nav=filet…=5&resource=global&prefermaskfilter=&maximumRecords=10&timezoneOffset=-330' was loaded over HTTPS, but requested an insecure script 'http://yacy.searchlab.eu/solr/select?query=&verify=false&nav=filetype,proto…cet.field=url_protocol_s&facet.field=author_sxt&facet.field=collection_sxt'. This request has been blocked; the content must be served over HTTPS.

**Comment by nikhilrayaprolu** [comment]
when you load a github page over https then for sure you will get this error, learn how to disable https in browsers on demo links since gh-pages doesn't allow deployment on http. You will understand these once you jump into contributing to some project and working with gh-pages. good that you have learnt something today.

**Comment by Orbiter** [comment]
@nikhilrayaprolu please be kind to each other and argue on a technical level only.

**Pull request closed without merging**
