### PR TITLE
Update the issue template

### LINKED ISSUE #1218: Update Issue Template
**I'm submitting a ...**
- [x] feature request
 

### Will work on it??
Yes

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #1218 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

Update issue template.

### CODE REVIEW

**Comment by sk9331657** [comment]
@simsausaurabh @praveenojha33  Can you help me ??  I am not able to understand why Travis is failing for this commit.

**Comment by rajvaibhavdubey** [comment]
You need to restart the travis, it may work then. Close and reopen it.

**Comment by sk9331657** [comment]
@rajvaibhavdubey  Thanks Raj. :+1:

**Comment by sk9331657** [comment]
@praveenojha33

**Pull request merged**
