### PR TITLE
#Fixes872: Font awesome and navbar inverse

### PR DESCRIPTION
**Pull request by aniket223**
screenshot-2018-1-9 susper

### CODE REVIEW

**Comment by harshit98** [comment]
@aniket223 Describe your changes you've done. I'm able to understand what you've done here and I don't think there is any need for change in the UI.

**Comment by aniket223** [comment]
https://pr-883-fossasia-susper.surge.sh/

link using surge

**Comment by bhaveshAn** [comment]
See https://pr-883-fossasia-susper.surge.sh/terms Here the navbar is not that which you made in other pages. Also in the new navbar you have not left space between the icon and Name of page. (so looking quite weird)
Consider the screenshot, here space is not between phone (icon) and Contact {the text), same in the case of other three.
screenshot from 2018-01-13 22-32-37

**Comment by aniket223** [comment]
I am new to open source so sorry for the 2 merge commits I made.
I have updated the terms page with navbar and added spaces to the font aweosme icons
screenshot-2018-1-14 susper

**Comment by aniket223** [comment]
@harshit98  i have added navbar inverse and font-aweosme icons , so the different pages of the site looks bettter

**Comment by harshit98** [comment]
There is no need to have navbar-inverse. Please close this PR @aniket223.

**Pull request closed without merging**
