### PR TITLE
Fixes #523,Pagination bar now appears

### LINKED ISSUE #523: Pagination bar not appearing.
**Actual Behaviour**

Pagination bar seems to be not appearing. 

**Expected Behaviour**

It should appear in all in the pages. To avoid this problem : create a `pagination` component instead of combining with results component.

**Screenshots of the issue**

screenshot from 2017-06-20 07-12-51

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #523 
Changes: Pagination bar is visible again, on all pages(fixed the error)

Demo Link: [Here](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 @nikhilrayaprolu Kindly review

**Comment by harshit98** [comment]
@Marauderer97 Why you have not created new Pagination component ? It would be better if we create a separate component for it and write tests. So that this problem won't occur again in future.

**Comment by Marauderer97** [comment]
@harshit98 This problem is not because there was no component, Do we need a seperate component for a piece of code that is required only once in the project? That is up for discussion. Besides how will we pass important parameters from results component to pagination such as the current page number, the total number of pages and the number of pages ahead? All of this, requires discussion among community members and might take time.For now, I have fixed the bug so that Susper has a pagination bar.

**Comment by harshit98** [comment]
There's #53 issue regarding refactoring results page into separate components. I thought it would be best time create a separate component for it. 

It would be great if we ask final decision from @nikhilrayaprolu as well. :+1:

**Comment by Marauderer97** [comment]
@harshit98 Yes, I agree. @nikhilrayaprolu What do you think?

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 @harshit98 I would suggest to break up results component into different components (similar to what loklak does) .we could pass the parameters using different component interactions (input and output) or using ngrx store.
But since above work takes the time we shall temporarily merge this pull to fix the bug and start working on refactoring the results page.

**Pull request merged**
