### PR TITLE
Fixes #861 : Developed a eventyay iconary, fixed broken icon and dimensions

### LINKED ISSUE #861: Fix the broken eventyay icon
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Broken **eventyay** icon in menu. (Also, in wrong dimensions. Should be in `48x48`)

**Expected behavior:**
Should display and can navigate to eventyay

---
**Screenshots of the issue:**

image

### PR DESCRIPTION
**Pull request by 0x48piraj**
# Fixes #861

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
image

- Procured the **eventyay** logo, fixed dimensions, enhanced quality.
- Fixed the icon, adjusted it to be responsive :tada:

### CODE REVIEW

**Comment by 0x48piraj** [comment]
@fossasia/susper-admin 

**_Here's my Deploy Link : https://pr-863-fossasia-susper.surge.sh_**

**Comment by 0x48piraj** [comment]
@the-dagger @daminisatya @fossasia/susper @fossasia/susper-admin Please merge :+1:

**Comment by 0x48piraj** [comment]
Would you mind merging it @nikhilrayaprolu ? :blush:

**Comment by abishekvashok** [comment]
Can you pls check travis?

**Comment by 0x48piraj** [comment]
Yes, I saw the Travis Check, It seems it's misconfigured.

**Comment by abishekvashok** [comment]
@0x48piraj I have solved it in #890

**Comment by 0x48piraj** [comment]
Then why it's failing ?

> Ref : https://travis-ci.org/fossasia/susper.com/builds/328501253

**Comment by harshit98** [comment]
@0x48piraj Can you open another pull request? Looks like Travis has been fixed recently. I can't re-run the build.

**Comment by 0x48piraj** [comment]
Travis fix PR is not merged, so the error is there.
@nikhilrayaprolu Please merge it, and squash also if needed. It will be much appreciated.

**Comment by gabru-md** [comment]
You can just close and open the same PR to run travis again @harshit98

**Comment by 0x48piraj** [comment]
@gabru-md Failed Again!

**Comment by 0x48piraj** [comment]
Seems like a order @aashutoshrathi :thinking: 
**_Sir, Yes Sir! Closing! 👍_**

**Pull request closed without merging**
