### PR TITLE
Fixes #683, susper now responsive on screen greater than 1920px

### LINKED ISSUE #683: On large resolution screens search bar disappears and design is distorted
Please test the site on large screens and ensure all page items appear as expected. See the bugs on large resolutions in the screenshot below, please.
screenshot from 2017-07-22 15-29-16

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #683 
Changes: Susper now responsive on screen greater than 1920px

Demo link: [https://marauderer97.github.io/susper.com/](https://marauderer97.github.io/susper.com/)

At very high sizes:
image
At moderately high sizes
image
At small sizes
image

### CODE REVIEW

**Comment by harshit98** [comment]
@Marauderer97 Would be great if you're able to shift the result feed content a little bit towards the right side, so it doesn't look much left aligned.

**Comment by harshit98** [comment]
@Marauderer97 Good work! Everything else looks good to me. :+1: :100:

**Comment by Marauderer97** [comment]
@harshit98 At what dimensions do you want me to shift the result feed? I am trying to align it to the search options as you pointed out in th pull on large screens. If I shift the results feed, won't the alignment and margins wrto the search bar get disturbed?

**Comment by mariobehling** [comment]
Looks good. Please change anything else that is needed in follow up PRs.

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
