### PR TITLE
Center Settings and Tools Menu Items

### LINKED ISSUE #1222: Items in Settings and Tools Menu are not Centered
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

In the search results section, the text in the Settings and Tools menu is not centered.

**Expected behavior:**

The text should be centered within the gray area.

**Screenshots of the issue:**

image

**I am working on this**

### PR DESCRIPTION
**Pull request by Ryan10145**
Fixes #1222 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [X] Added Surge preview link

#### Changes proposed in this pull request:

- Changes the padding on the Results Settings menu to center the text vertically 
- Changes the padding on the Results Tools menu to center the text vertically

- https://pr-1223-fossasia-susper.surge.sh

image
image

### CODE REVIEW

**Comment by Ryan10145** [comment]
@rajvaibhavdubey The purpose of the change is to center the text vertically within each box, not horizontally. Before, the text would be much farther off center, which is what my change fixes. I’ve updated my PR description to clarify this.

**Comment by rajvaibhavdubey** [comment]
> @rajvaibhavdubey The purpose of the change is to center the text vertically within each box, not horizontally. Before, the text would be much farther off center, which is what my change fixes. I’ve updated my PR description to clarify this.

OK Cool :+1:

**Comment by Ryan10145** [comment]
Can someone merge this/take a look at this? Thanks! @praveenojha33 @simsausaurabh @mariobehling

**Comment by mariobehling** [comment]
Please follow Google's approach. It is not centered there. Thank you.

**Comment by Ryan10145** [comment]
@mariobehling In Google, the text is centered vertically though? The padding on the Google version is much smaller, which should be changed, but Google does have the text centered within each box as far as I can tell. My change only centers the items vertically, not horizontally, which may be a point of confusion.
image

**Pull request merged**
