### PR TITLE
Fixes #1124: Improved Sidebar Top providers and Top authors

### LINKED ISSUE #1124: Fix and improve sidebar of top providers and top authors
* Reduce green area around numbers to 0.1em padding and 1px border radius
* Show max 50 top providers and top authors and show an option to open more below (after expanding it initially)
* Open more than 50 providers in a lightbox
* Show expandable box below search results in mobile view (currently the sidebar disappears) 

screenshot from 2018-07-24 16-47-50

### PR DESCRIPTION
**Pull request by praveenojha33**
Fixes #1124 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Improved Sidebar Top providers and Top authors:
1)Reduced green area around numbers to 0.1em padding and 1px border radius.
2)Showed only 50 top providers and top authors and created an option to show all providers in light box.
3)Implemented a lightbox to show all providers/authors.
4)Expandable box is present below search results in mobile view.(Currently there is no lightbox for smaller screens)

- https://pr-1145-fossasia-susper.surge.sh

image
image

### CODE REVIEW

**Comment by praveenojha33** [comment]
@simsausaurabh Please clear your cache.It is working fine for me.

**Comment by mariobehling** [comment]
* Design - font/color - should be same as in sidebar

**Comment by mariobehling** [comment]
* Change "Show All Provider" to the correct "Show all Providers" and make it into a box same as "Chart Analytics".

**Comment by praveenojha33** [comment]
@mariobehling I have made requested changes. Please review.

**Pull request merged**
