### PR TITLE
Fixes #527 now search button is removed similar to google

### LINKED ISSUE #527: susper has a search icon on home page but google has an empty search bar without search icon on home page
google has no search icon on the front page but susper has a search icon remove the search icon.remove the search icon on the home page of susper.
image

image

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
Fixes issue #527 
Google:-
image
Susper:-
image

removed the search button on homepage
Demo Link: https://susper-pr-540.herokuapp.com/

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
@harshit98 updated the branch

**Comment by mariobehling** [comment]
@nikhilrayaprolu Please see the black line below, which is in the center of the search box. Do you see that the centre of the logo and the centre of the box are not centered?

27440913-b190fc2e-5789-11e7-8c1d-92d466aa1230

**Comment by harshit98** [comment]
@nikhilrayaprolu any status regarding this PR? :)

**Comment by nikhilrayaprolu** [comment]
centered logo with search bar
image

**Pull request merged**
