### PR TITLE
Fixes positioning of no results text in image search

### PR DESCRIPTION
**Pull request by ajayns**
Fixes issue #634 

Changes: Positioning of no results text changed for image search such that it matches that of basic results and video results. Also fixed line height issue for the text in mobile screens.

Screenshots for the change: 
Before
image

After
image
image

### CODE REVIEW

**Comment by harshit98** [comment]
@ajayns Please align the `Did you mean..` and no results found details. They both should be aligned properly together and w.r.t alphabet 'A' of `All` tab.

**Comment by ajayns** [comment]
@harshit98 Yeah this issue was persisting since before so I thought that was the expected behaviour. I'll work on this right away

**Comment by harshit98** [comment]
@ajayns Please do the changes and update the PR.

**Comment by ajayns** [comment]
I seem to facing issues getting full responsive behavior as you mentioned. Right now the the `did you mean` and no results text seems to aligned fine in large screens and when it comes to small, It goes to the edges. Been traveling and so will work on it in a while. @harshit98

**Comment by ajayns** [comment]
@harshit98  Sorry about the delay. But here are the updated changes: 
screen shot 2017-10-19 at 11 25 11
screen shot 2017-10-19 at 11 25 01
screen shot 2017-10-19 at 11 24 50

**Comment by ajayns** [comment]
@harshit98 Okay great thanks, will look into others. @mariobehling Please review and merge PR.

**Pull request merged**
