### PR TITLE
Fixes #261 Alignment of rendered images

### LINKED ISSUE #261: Align the rendered images under 'images section' following the market leader
Image search in susper - 

selection_036

Image search in Google - 

selection_037

### PR DESCRIPTION
**Pull request by harshit98**
Resolves #261 

Previously had some problems with merge conflicts due to which not able squash commits. See #263 

Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>.

Things I have done in this PR : 
- I have scaled the images to a common height maintaining their ratio as well.

Screenshot : 

selection_047

Problems : 
- Due to broken link of the images, a lot of white space is being left. See issue #108 , previously I did some work on it. But looks like it not working as we want.

What it looks like : 

selection_046

What is happening actually : 

selection_048

### CODE REVIEW

**Comment by harshit98** [comment]
@nikhilrayaprolu okay, working on it. :+1:

**Comment by harshit98** [comment]
@nikhilrayaprolu Well I tried to solve it but, looks like problem still persists. However, this issue has solved the alignment problem. : )

Updated preview link - <a href="https://harshit98.github.io/susper.com/">here</a>

**Comment by nikhilrayaprolu** [comment]
@harshit98 raise an issue regarding the images not rendering,
also don't crop the images, I find them cropped.

**Comment by harshit98** [comment]
Done! @nikhilrayaprolu 

Updated demo link - <a href="https://harshit98.github.io/susper.com/">here</a>.

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
