### PR TITLE
Fixes #462, width and position of Infobox more like market leader

### LINKED ISSUE #462: Match position and width of info box
The position and width of info box is not matching market leader. Please ensure the box is covering the same width.
screenshot from 2017-06-09 01-21-03

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #462 

Changes: This Pr does the following 

- [x] reduces the width of the info box to follow market leader

- [x] increases the margin of the info box at the top to follow the market leader

- [x] Shifts the position of the infobox so that the right margin remains the same even after reducing the width of the info box

Demo Link:[Here](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 
image

image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 @sandeepm96 @isuruAb @nikhilrayaprolu Please review :)

**Comment by harshit98** [comment]
@Marauderer97 At present infobox is not appearing. How did you solved this issue ?

**Comment by Marauderer97** [comment]
@harshit98 Try refreshing the page please
image

**Comment by mariobehling** [comment]
@Marauderer97 

Please check the box in different resolutions. It needs to be responsive. With Google the box has different sizes in different resolutions. Actually at points it is bigger than our box.

**Comment by Marauderer97** [comment]
image
image
image
image
image
image

Made changes to make the width proportionate to the viewport width

**Comment by mariobehling** [comment]
Your changes are not an improvement.

1. The width does not correspond in a number of resolutions to the market leader
2. You changed the position of the box in a way that it is not always on the same line with the top search results.
3. The position of the tools button is changing as well for no reason

**Comment by mariobehling** [comment]
I am unclear why you are posting all the screenshots from Google here also.

Expected: If you post screenshots, post Google and Susper screenshots next to each other.

**Comment by Marauderer97** [comment]
@mariobehling 

-  I have made the info box responsive to all screen sizes matching Google now

-  I have set the infobox position so that the border coincides with the topmost result now

-  I have not changed the Tools position at all, this bug was there even previously in Susper

image
image
image

**Pull request merged**
