### PR TITLE
Fixes #1063: Match the Top gray bar to Google

### LINKED ISSUE #1063: Match the top bar gray
The top bar gray on Susper.com is darker than on Google.com. Please match the color on Susper.

### PR DESCRIPTION
**Pull request by khyatidoshi**
I have changed to color for the top gray bar of susper.com to match it with google.com.
Surge Link: https://pr-1074-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@khyatidoshi Please provide the PR review link of surge, as described in the PR template.

**Comment by khyatidoshi** [comment]
@simsausaurabh thankyou. Will squash the commits from next time.

**Comment by praveenojha33** [comment]
@khyatidoshi Please tell the status of this PR. We need to solve the issues quickly.

**Comment by khyatidoshi** [comment]
@praveenojha33 the text is in grey which is unchanged, please check and let me know if the problem still persists.

**Comment by praveenojha33** [comment]
@khyatidoshi Please see my updated comment there are some more issues. Just open Susper.com and your PR surge link in alternate tab and see the difference.

**Comment by praveenojha33** [comment]
@khyatidoshi Are you seeing the issue which I have mentioned locally. Please let me know.

**Comment by khyatidoshi** [comment]
@praveenojha33 I am not able to solve it..

**Comment by simsausaurabh** [comment]
@khyatidoshi We are here to help you out. Let me go through the issue mentioned by @praveenojha33.

**Comment by simsausaurabh** [comment]
@praveenojha33 I am not able to reproduce the bug clearly. Please check again if everything is fine, it can be merged.

**Comment by khyatidoshi** [comment]
@praveenojha33 no I couldn't.

**Comment by praveenojha33** [comment]
@khyatidoshi I was getting some color issues, because of cache files(I think). It looks good now. Try fixing some other issues. Keep Up the good work :+1:

**Pull request merged**
