### PR TITLE
Fixes #1122 Next Button Location

### LINKED ISSUE #1122: Previous and Next are not working
Previous and Next link have issues. Please fix it:
* The links don't always work
* The area is moving on different pages. It should not move and always be in the same location

screenshot from 2018-07-24 16-34-58
screenshot from 2018-07-24 17-02-57

### PR DESCRIPTION
**Pull request by khyatidoshi**
Fixes #1122 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Fix the problem caused by wrong media query value (`426` instead of `425`)
- Set a fixed value for `padding-top` in `page-item2` as the item was moving around as we change the screen size. The fixed value does not cause any problem with the mobile devices of varying screen sizes as well.

- https://pr-1146-fossasia-susper.surge.sh

-

### CODE REVIEW

**Comment by praveenojha33** [comment]
@khyatidoshi What is the status of this PR?

**Comment by praveenojha33** [comment]
@khyatidoshi Please see this 
image
Also please tell the status of the PR. It is taking a very long time. The changes you have made are causing problems.

**Comment by khyatidoshi** [comment]
@simsausaurabh I'm not able to solve it. Fixing the location on desktop view creates issues on mobile view.

**Comment by praveenojha33** [comment]
@simsausaurabh Please review.

**Comment by mariobehling** [comment]
Test deployment does not load for me.

**Comment by praveenojha33** [comment]
@mariobehling It is working for me.
image

**Comment by mariobehling** [comment]
Good job! Thanks.

**Pull request merged**
