### PR TITLE
add infobox twitter

### LINKED ISSUE #1235: Add a Twitter Discussion on Infobox
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

There Is no Twitter Link for Infobox
**Expected behavior:**

There should be

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by pythongiant**
Fixes #1235

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Add a twitter link for infobox

- https://pr-1236-fossasia-susper.surge.sh 

image

### CODE REVIEW

**Comment by pythongiant** [comment]
image

**Comment by pythongiant** [comment]
@AakashMallik the indentation ?.

**Comment by pythongiant** [comment]
image

**Comment by pythongiant** [comment]
@simsausaurabh The point of it is to checkout discussions on twitter not twitter profiles. I hope that's alright?

**Comment by AakashMallik** [comment]
> image

Yeah, The code within the <p> tags. I just felt it should be indented, it is totally up to you whether or not you wish to go the extra mile.

**Comment by pythongiant** [comment]
@AakashMallik doing the changes right now

**Comment by pythongiant** [comment]
done @AakashMallik

**Pull request merged**
