### PR TITLE
index page changed to google theme

### PR DESCRIPTION
**Pull request by sj29-innovate**
I have tried to change the index page as per google theme.Please have a look and give suggestions.
I will then work on the top bar.

### CODE REVIEW

**Comment by mariobehling** [comment]
Hi, please provide screenshots and a link to a sample page on your github repository. Cheers.

**Comment by sj29-innovate** [comment]
This is how the index page looks like.
index
As of now i have only made changes to the index page search bar.

**Comment by mariobehling** [comment]
Thanks. Please provide a link to your test repository.

The search button seems much smaller than what Google uses. Please improve details of the search buttons.

**Comment by sj29-innovate** [comment]
https://github.com/sj29-innovate/susper.com
This is the link to my repository.Thanks for your feedback.Will work upon it.

**Comment by sj29-innovate** [comment]
searchbtn
Search Button is larger now.

**Comment by mariobehling** [comment]
Thanks. In order to achieve a page that uses the Google theme on the start page, what other changes should be made, e.g. no gray top bar, implement bottom bar? Please compare.

screenshot from 2016-12-07 07-37-24

**Comment by sj29-innovate** [comment]
Do we need to make changes to the navigation bar other than shifting it to the bottom.Google has some links in the bottom bar.I have shifted the navigation bar to the bottom of the screen now.What more changes can be made?
navbottom

**Comment by mariobehling** [comment]
Thanks. Please help to make the bottom bar closer to the Google theme and take out the logo.

**Comment by sj29-innovate** [comment]
Yes i am already working on making it look closer to google . Thanks for your feedback

**Comment by sj29-innovate** [comment]
Made some more changes.I think now the bottom bar looks very close to google without the links though.
Your feedback required.
gl

**Comment by mariobehling** [comment]
Good job! Let's merge and add other parts step by step.

**Comment by sj29-innovate** [comment]
Yes Sure!
I will start working on moving the search bar to top.

**Comment by mariobehling** [comment]
I need to revert this change as there are issues with the UI. Please fix and commit again.

* Search button below search in result page
screenshot from 2016-12-10 21-51-07

* Search button not centered.
screenshot from 2016-12-10 21-51-23

**Pull request merged**
