### PR TITLE
Search engine UI fix

### LINKED ISSUE #1502: Search bar not fixed at top
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
When we scroll the window the search bar also gets scrolled.

**Expected behavior:**
The search bar should be fixed as in google search.

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes #1502 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
When we scroll the window search bar is fixed just like in google search.

- https://pr-1503-fossasia-susper.surge.sh

### CODE REVIEW

**Review by praveenojha33 — CHANGES_REQUESTED** [review]
I did not get what issue you are solving, please attach screenshot of the issue.

**Comment by Dishebh** [comment]
@praveenojha33 I just realised, the issue I am solving is already fixed in the dev branch but the website (susper.com) is somehow, not in sync with the default branch. How?

I am simply making the search bar fixed at top when the user scrolls down through the results.

**Comment by praveenojha33** [comment]
@Dishebh There are many changes in dev branch which need some review from other developers and maintainers and then only we can sync it with the main branch. So as you have already pointed out that this issue has already been solved therefore I am closing it. Thank You for your contribution.
Cheers :sparkle:

**Comment by Dishebh** [comment]
@praveenojha33 can you pls have a look at my other PRs as well? Thanks!

**Pull request closed without merging**
