### PR TITLE
Fixes #508 Implement Voice Search for Susper (Chrome only)

### LINKED ISSUE #508: Implement Voice Search for Chrome
Using Google with Google Chrome it is possible to make a voice search. Please implement the same for Susper and automatically show the voice icon with the same functionality.

screenshot from 2017-06-17 16-43-00

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #508 

Changes: Implemented voice search for Susper which will work only for Chrome.

Demo Link: https://harshit98.github.io/susper.com/

Screenshots for the change: (Not appropriate here)

Go to preview link. Click on microphone icon : then a pop up will display asking to allow microphone service. Allow it and speak a query as a single keyword and it will load the results.

Kindly review @nikhilrayaprolu  @Marauderer97

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98  demo link not working please check

**Comment by harshit98** [comment]
@mariobehling done! now the mic icon will only appear in Chrome.

Screenshots : 

Chrome
screenshot from 2017-06-19 05-52-01

Firefox
screenshot from 2017-06-19 05-52-21

@Marauderer97 : done the changes as you suggested. :+1:

**Comment by mariobehling** [comment]
@harshit98 Please resolve merge conflicts.

**Comment by harshit98** [comment]
@mariobehling done!

**Pull request merged**
