### PR TITLE
Fixes #2 Added test

### LINKED ISSUE #2: add codecoverage scripts , html linters
adding the codecoverage , and html linters would make the code quallity better and easier to view and understand. one picking up this issue needs to correct html lint errors present in the project too.

- [ ] add codecoverage

- [ ] add html linter and correct lint errors present

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #2 :)
Similar - #64

### CODE REVIEW

**Comment by harshit98** [comment]
@nikhilrayaprolu - Regarding the HTML Lint errors, I'll fix them and make a new PR regarding to that. :)

**Comment by harshit98** [comment]
@nikhilrayaprolu Done. We can merge now. :)

**Comment by Abhi2424shek** [comment]
Pls squash the commits into one :P

**Comment by nikhilrayaprolu** [comment]
looks like there are some conflicts in this pull resolve them @harshit98

**Pull request merged**
