### PR TITLE
Search bar is fixed when scrolled

### LINKED ISSUE #1353: Search bar fixed when window is scrolled
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
When we scroll the window the search bar also gets scrolled.

**Expected behavior:**
When we scroll the window search should be fixed just like in google search.

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #1353

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

When we scroll the window search bar is fixed just like in google search.

- https://pr-1354-fossasia-susper.surge.sh

search

### CODE REVIEW

**Comment by subhahu123** [comment]
screenshot from 2018-12-28 12-42-44
why is footer is not on his place 
comparing to current susper.com
screenshot from 2018-12-28 12-43-59
@samagragupta

**Comment by samagragupta** [comment]
@shreyanshdwivedi Done the required changes.

**Comment by samagragupta** [comment]
@simsausaurabh Please review.

**Comment by shreyanshdwivedi** [comment]
@samagragupta any update on this PR?

**Comment by samagragupta** [comment]
@praveenojha33 @shreyanshdwivedi Done the changes.

**Comment by samagragupta** [comment]
@simsausaurabh @praveenojha33 Please merge it.

**Pull request merged**
