### PR TITLE
fixes #1179 (added magic mirror,yaydoc,meilix and Phimp.me to navbar …

### LINKED ISSUE #1179: Add SUSI.AI for Magic Mirror, Yaydoc, Meilix and Phimp.me in Projects section under the menus icon in the navbar
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Presently we have only badgeyay,eventyay,loklak,susi,fossasia and pslab which appears on clicking on menus icon on the navbar. We should include Phimp.me, Meilix, Yaydoc and SUSI.AI for Magic Mirror also as they are important FOSSASIA projects. The meilix project already includes them.

**Screenshots of the issue:**

Meilix navbar:
aspectratioprb
SUSPER navbar:
contactinsusper

### PR DESCRIPTION
**Pull request by sarnava1**
…dropdown

Fixes #1179

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Added Surge preview link

#### Changes proposed in this pull request:

-This PR adds meilix,susi.ai for magic mirror,yaydoc and phimp.me in the navbar dropdown

- https://pr-XXXX-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by sarnava1** [comment]
@simsausaurabh @mariobehling  @hongquan  @bhaveshAn @niranjan94 can you please guide me on this travis checks. I don't know why the PR is failing the travis check. Please review my PR.

**Comment by sarnava1** [comment]
@simsausaurabh I will make the changes

**Comment by praveenojha33** [comment]
Closing this due to inactivity. Also another PR has been merged with these changes.

**Comment by sarnava1** [comment]
@praveenojha33 thanks. Actually another PR was opened by someone when I was not active and that PR has been merged. So, this should have been closed. I apologise for not closing it.

**Comment by praveenojha33** [comment]
@sarnava1 No need to apologise brother. Thank You for the issue and the PR.

**Pull request closed without merging**
