### PR TITLE
Overlapping removed

### LINKED ISSUE #1283: Overlapping of drop down menu on search field
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

**Will work on the issue:**
Yes, I will work on the issue.

### PR DESCRIPTION
**Pull request by plxity**
Fixes #1283 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Overlapping in removed 

- https://pr-1284-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by plxity** [comment]
@simsausaurabh It's working perfectly fine.

**Comment by plxity** [comment]
@praveenojha33 okay, then what can be done to remove that bug?

**Comment by praveenojha33** [comment]
@plxity We can change size of service box according to different screens. :+1:

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Pull request closed without merging**
