### PR TITLE
Addresses #571 basic implementation of Maps feature

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
Addresses #571
Basic component and leaflet implementation of Maps Feature,
 Later we have to geocode the searches made and show pointers on Map.
features like buttons to zoom and extra features supported by open street and leaflet could be implemented.

Demo Link: https://susper-pr-587.herokuapp.com/

Screenshots for the change: 
image

### CODE REVIEW

**Comment by harshit98** [comment]
@nikhilrayaprolu Kindly solve codacy error. : )

**Comment by nikhilrayaprolu** [comment]
@harshit98 that is standard leaflet CSS by leaflet community. so, for now, we could ignore codacy for this pull.

**Comment by harshit98** [comment]
@nikhilrayaprolu Looks good to me. We can merge this. :+1: 

This won't affect the future PRs since it is codacy error.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by mariobehling** [comment]
Actually, it is still unclear how this is supposed to work in a search engine and my comment did not get answered. Please answer in detail how this is relevant in a search engine and how this should work. Which queries should this answer at the moment? Why do we need to use SUSI here? What could be an implementation without SUSI?

Because of open questions I am closing this.

https://github.com/fossasia/susper.com/issues/571#issuecomment-312697479

**Comment by nikhilrayaprolu** [comment]
Regarding the maps feature,
**Why Maps feature?**
 Google has it in their search options, so we thought it would be a very good feature to add in susper.
image

**How should this work?**
when a user types something like "Hot spicy food in Hyderabad" it gives search results on maps showing the best restaurants/hotels in hyderabad.
image
image
also if user types "**where is Berlin?**" it shows Berlin in maps
image
**why do we need to use SUSI here?**
presently, SUSI has some skills related to queries like this related to maps. and since SUSI is extensible we could expect some more features to get added into SUSI skill set related to maps and this will be a very good use case for SUSI intelligence.
presently SUSI supports queries like "where is India" or just "India" which returns us a response with coordinates of places. which can be used to show the positions of places in maps in Susper similar to Google.
**what could be an implementation without SUSI?**
there are many geocoding APIs available for implementation of searches in maps. for instance with OpenStreetMap API if a user searches for "Berlin" we can get coordinates of berlin, but if a user searches for "**where is berlin?**" OpenStreetMap **doesn't return any results** due to lack of Intelligence.
image
to even show map results for queries like "where is berlin?" we need to use a bit of AI decoding like in SUSI.

**Comment by mariobehling** [comment]
@nikhilrayaprolu Ok, thanks for the answer. Please go back to the issue and:
1. Add "what we want to achieve with a maps features". 
2. Add services that help us to achieve this, e.g. route or location
3. Outline a plan where maps can be integrated into our service.

Map services are a whole new topic and even Google does not take care of map services within their search engine, but they have it as a component under maps.goo...

Still they also offer map services as an info box component. So a start might be to add a map into the info box for questions like "Where is India" and get that answer from SUSI. All of these should be documented right away in our docs, e.g. answering - what service are we adding, what questions does it answer, what is the expected outcome, where does it show up.

**Pull request closed without merging**
