### PR TITLE
[Fixed 1st point of #1208] Add a clock widget 

### LINKED ISSUE #1208: Add widgets
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behaviour:**
Add widgets to the main interface.
- [ ] Clock widget
- [ ] Weather widget
- [ ] Calendar widget

**Am I working**
Yes, I do.

### PR DESCRIPTION
**Pull request by STEdirisuriya**
Fixed #1208 Point 1 (Add a clock widget)

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
Added a clock widget.
 https://pr-1209-fossasia-susper.surge.sh

image

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
@praveenojha33 I think majour search engines have their widgets for help user and beautify the interface. In this case I think this hoverble clock widget will help to do it for SUSPER.

**Comment by STEdirisuriya** [comment]
@rajvaibhavdubey @praveenojha33 Why you think so? It's hover-able when user move pointer to it it's showing.

**Comment by STEdirisuriya** [comment]
@mariobehling Is this no need to SUSPER? Am I close this?

**Comment by simsausaurabh** [comment]
@STEdirisuriya There are a lot of prior issues, and currently it is not our priority. We will look for it in future if required. For now, we are keeping it simple.

**Comment by STEdirisuriya** [comment]
@praveenojha33 Am I close this?

**Pull request closed without merging**
