### PR TITLE
Fixes #1014: Made infobox responsive

### LINKED ISSUE #1014: Wikipedia tab collide with page content on different screen dimensions
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Wikipedia tab is colliding with page content on different screen dimensions.

**Expected behavior:**

The Wikipedia tab should disappear on a window size smaller than x pixels (width) or should behave like a show-hide effect.

**Screenshots of the issue:**

susper

### PR DESCRIPTION
**Pull request by praveenojha33**
Fixes #1014

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
In this PR the Infobox has been made responsive for some smaller screen sizes.
This change can might disturb the appearance of other components (when we will have results) like Analytics box and other components. As I am unable to see how this change affect other components.
But for now this can be used as a fix.Later on when we will have results back we can fix UI.

Surge: https://pr-1015-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@praveenojha33 infobox is not appearing in window pixel(px) range: ```768xXXX-1100xXXX``` and infobox is not aligning with intelligence section box with window pixel(px) range: less than```512xXXX```. (Here ```XXX``` means any value and ```x``` means e.g. ```123x456```).


1.
screenshot from 2018-06-02 23-25-12
---
2.
screenshot from 2018-06-02 22-27-39
---

**Comment by ValentinBercaru** [comment]
On the desktop version everything works fine :+1:  but on mobile version the elements are not alligned

pp

**Comment by praveenojha33** [comment]
@ValentinBercaru @simsausaurabh  Thank You for review,  I think responsiveness for mobile needs some work, but we can't work on it until we are getting steady results from YaCy . There are so many components present and messing with infobox disturbs other components(which might not be visible when there are no results ). Further when results are displayed the infobox is not organised well, for this please see over Mario's comment at last here https://github.com/fossasia/susper.com/pull/1011 . I made the styling of infobox similar to previous one( i.e When we were using DBpedia) . I think for now I am going to put it the same way as it was before ( i.e When we were using DBpedia) and later on when we will get steady results we can work on responsiveness for mobile and other screens.
Thank You

**Comment by praveenojha33** [comment]
@ValentinBercaru This PR will fix #1014 and for responsiveness and UI of Analytics Box and Infobox, I have opened a more generic issue here #1016 . Please approve this PR so that we can have infobox restored as it was previously. As currently it might can cause this problem when we will have results 
https://user-images.githubusercontent.com/33882273/40879669-1b6c17c8-66ac-11e8-8596-29cac0c24823.png

**Comment by praveenojha33** [comment]
Results are coming now I am closing this PR for now. Will make a separate PR that will fix #1016 #1014 #1013

**Pull request closed without merging**
