### PR TITLE
Adding Resource prioritization ( increasing light house performance )

### LINKED ISSUE #898: Increase Lighthouse Performance of Susper
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

image

**Current behavior:**
- Progressive web app
  - [x] The App does not provide fallback content when Javascript is not available.
  - [x] User is not prompted to install the Web App ( prompt for adding to home screen)
  - [x] Adding manifest.
  - [x] Address bar does not match brand colors
- Performance
  - [ ]  Does not Reduce Render-blocking script.
  - [ ]  Does not Reduce Render-blocking stylesheets.
- Accessibility
  - [ ]  Image elements do not have [alt] attributes.
  - [ ]  Form elements do not have labels.
- Best Practices
  - [ ]  Does not Opens External Anchors Using rel="noopener" .

**Expected behavior:**
All the Issue mentioned above should be resolved.

I am working on these Issue. I have made a checklist, will resolve each issue one by one 👍 
Please give suggestions @mariobehling  @harshit98 @nikhilrayaprolu

### PR DESCRIPTION
**Pull request by subhahu123**
Addresses #898

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

-

- https://pr-1425-fossasia-susper.surge.sh

-

### CODE REVIEW

**Review by neeraj3029 — APPROVED** [review]

**Review by praveenojha33 — COMMENTED** [review]
Please make it addresses #898 instead of fixing #898

**Comment by subhahu123** [comment]
> Please make it addresses #898 instead of fixing #898

sorry.........
but what ..???

**Comment by praveenojha33** [comment]
@subhahu123 In your PR message change "Fixes #898 " to "Addresses #898 " as this issue is not completely fixed by this PR.

**Comment by subhahu123** [comment]
Ok

**Comment by subhahu123** [comment]
@praveenojha33 done

**Comment by shreyanshdwivedi** [comment]
@subhahu123 any reference to resource?

**Review by sakshee-19 — APPROVED** [review]

**Review by simsausaurabh — APPROVED** [review]

**Pull request merged**
