### PR TITLE
Angular Cli installation command update

### PR DESCRIPTION
**Pull request by sharang108**
Angular Cli package is updated, for more information please visit following links [one](https://www.npmjs.com/package/@angular/cli), [two](https://stackoverflow.com/a/42452061).

### CODE REVIEW

**Comment by harshit98** [comment]
@sharang108 
Do `git rebase -i HEAD~N` where N = no. of commits and squash your commits. Thank you!

**Comment by harshit98** [comment]
@sharang108 which issue it is related to ? Always, open up an issue for a bug which you're solving from next time.

**Comment by sharang108** [comment]
@daminisatya @harshit98 I raised an issue https://github.com/fossasia/susper.com/issues/330 related to this.

**Comment by sharang108** [comment]
@harshit98  Is this okay https://github.com/sharang108/susper.com/commit/dc112db1f262c83478c936a712341062a065ebfd

**Comment by harshit98** [comment]
Take a look at other PRs @sharang108 . After sqaushing commits, there should be always 1 commit in PR. Right now it is showing 7 commits in this PR. Looks like maybe you have not performed force push after squashing. `git push origin master -f` <- use this.

**Pull request merged**
