### PR TITLE
Fixes #512 crawl button design enhanced

### LINKED ISSUE #512: Increase space on crawler page between bottom area and footer and move button
Please change the following:
* The space between the bottom of the page and the footer is too small. Please increase it.
* Move the submit button to the right and increase its size
screenshot from 2017-06-19 08-38-33

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
Fixes issue #512 

Demo Link: https://susper-pr-519.herokuapp.com/

Screenshots for the change: 

image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Please check with codacy, also squash and merge

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 this was the same issue you faced with codacy regarding gradients in your previous pull, which is an error with from the codacy side lints.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 done squashed :+1:

**Comment by mariobehling** [comment]
Increase the space below the blue button more, please.

**Comment by nikhilrayaprolu** [comment]
image

@mariobehling done.

**Pull request merged**
