### PR TITLE
Fixes #814: search query is not selectable

### LINKED ISSUE #814: The search query is not selectable
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Currently, when we click on suggestions, only the part where the text is placed is selectable and clickable.

**Expected behavior:**
Whole suggestion row should be clickable

**Screenshots**

screen shot 11-17-17 at 05 47 pm 001
screen shot 11-17-17 at 05 47 pm

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #814 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Added `display: block;` to suggestions class, so that whole row is selectable.

#### Demo
http://acrid-train.surge.sh

#### Screenshots

screen shot 11-17-17 at 06 29 pm 001
screen shot 11-17-17 at 06 29 pm

### CODE REVIEW

**Comment by harshit98** [comment]
@aashutoshrathi Good! Please change the PR name and commit name. Commits should be squashed. Kindly follow the best practices. :)

**Comment by harshit98** [comment]
@aashutoshrathi The commit message should be `Fixes #814: ...`. Kindly provide a demo link too so that it will be much easier for the mentors to review the PR.

**Comment by aashutoshrathi** [comment]
@harshit98 update review

**Comment by aashutoshrathi** [comment]
@harshit98 demo link added

**Pull request merged**
