### PR TITLE
Added some test buttons to theme component

### PR DESCRIPTION
**Pull request by ValentinBercaru**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- I checked the dependencies from Gemfile.lock ( according to @mariobehling advice ) and everything seems to be up to date, so I added two buttons to test the current themes to see where is the problem with the nightTheme. I also changed a little bit the nightTheme from `src/app/theme/theme.component.ts`.

- updated the version of bundle in Gemfile.lock

- https://pr-983-fossasia-susper.surge.sh/ - surge link

### Screenshot

screenshotfrom2018-04-0922-26-45

### CODE REVIEW

**Comment by praveenojha33** [comment]
Hello @ValentinBercaru Please explain about this PR.

**Comment by praveenojha33** [comment]
@harshit98 Please review this. :innocent:

**Comment by ValentinBercaru** [comment]
@praveenojha33 I wanted to see if the additional buttons related to other themes works. This way I check if the html code for my theme doesn't work. 😊

**Comment by praveenojha33** [comment]
There is no problem with the implementation of themes. That is fine  All the latest PRs which are merged are not working on susper.com
In spite of your PR related to theme you can see these PRs #979 #949 in which only minor changes are made to HTML and CSS and they too are not working. So there is no need for doubting your implementation of theme.

**Comment by ValentinBercaru** [comment]
@praveenojha33 I wanted to see how many buttons would appear if I'll add two buttons for (e.g) terminalTheme. It is possible to appear only one and if this would happen it is not any problem with my implementation.

**Comment by ValentinBercaru** [comment]
I also said on gitter that I'll remove the changes from this PR after I'll see what happens.

**Comment by praveenojha33** [comment]
Please reply to my message on gitter.

**Comment by harshit98** [comment]
This PR can be closed. @ValentinBercaru. Maybe you need to require to update the project dependencies and version bump of Angular.

**Pull request merged**
