### PR TITLE
Addresses #121 Add autocomplete configure files

### PR DESCRIPTION
**Pull request by harshit98**
Addresses: #121 
This PR has been created to get started with autocomplete feature of susper search. Autocomplete files are not linked with search and result component at present, as I'm unable to figure out how to link them and show suggestions as Google does.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a link to a test page and describe your plan in the relevant issue.

**Comment by nikhilrayaprolu** [comment]
@harshit98 I am not able to find any of the features in the production. Did you face any problem and need to add more code to this pull?

**Comment by harshit98** [comment]
@nikhilrayaprolu I have just added the file with the code. The feature has not been linked to susper because, I was unable to figure out how it should be linked. Also, it may require some minor changes in code like how the suggestion should take place from the server.

**Comment by harshit98** [comment]
@mariobehling The plan was to implement the autocomplete feature in susper. This the required code I have written for autocomplete. I was not able to apply this feature to susper because there is one more feature which has been implemented in file `index.ts` under `reducers` folder. `index.ts` is for auto search feature and both the features were clashing with each other.

**Pull request merged**
