### PR TITLE
Fixes #648: Susper gives Listening... message on speech UI after sometime

### LINKED ISSUE #648: google gives message Listening... on speech UI after some time
implement Listening text similar to google on speech UI.
**Screenshots of the issue**

Attach a screenshot of the issue here.
image

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #648 

Changes: 
- when a user speaks, it will show "Listening..." message.

Demo Link: https://harshit98.github.io/susper.com/

Kindly review @nikhilrayaprolu @Marauderer97

### CODE REVIEW

**Comment by harshit98** [comment]
Done @nikhilrayaprolu

**Comment by nikhilrayaprolu** [comment]
@harshit it is not working as expected. see how google speech works.
https://www.youtube.com/watch?v=k6Vt8myLCxI&feature=youtu.be

**Comment by harshit98** [comment]
@nikhilrayaprolu Should I apply transition effect to "Listening..." using css?

**Comment by harshit98** [comment]
There are some wrong commits due to which it is not able to squash commits. I will open up a new PR.

**Pull request closed without merging**
