### PR TITLE
Fixes #316, Padding for contact form link removed

### LINKED ISSUE #316: Lot of space between keywords in contact page
Maintain the margin. In the screenshot, there is a lot if space after `contact link`

screenshot from 2017-05-21 19-37-39

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes #316, 
Padding for contact form link removed to prevent extra space.
image
Demo link -[Here](https://marauderer97.github.io/susper.com/)

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 I didnot change to pointer, because there was already a PR doing the same, see #313

**Comment by Marauderer97** [comment]
@AnshulMalik I agree working on it

**Comment by Marauderer97** [comment]
New test link https://susper-pr-317.herokuapp.com/

**Comment by AnshulMalik** [comment]
I can't see my previous comment :O

**Comment by harshit98** [comment]
@Marauderer97 Okay. We're good to merge this then. :+1:

**Comment by daminisatya** [comment]
Thank you @Marauderer97

**Pull request merged**
