### PR TITLE
Fixes #139 Update README.md

### LINKED ISSUE #139: Update README.md
There are some minor errors in README.md file. 

This should not be showing `build : error`. Travis is working fine. Also, **Communication** heading should look like a heading.
selection_029

Spelling mistakes. It should be 'angular'.
selection_030

Add this - if someone wants to update the Angular-CLI as it is very much helpful to overcome the problems while setting up it on local environment.
selection_034

There is no branch with name 'development'.
selection_033

### PR DESCRIPTION
**Pull request by harshit98**
This PR fixes and closes issue no #139  

Check <a href="https://github.com/harshit98/susper.com/blob/harshit98-patch-1/README.md">here</a>

### CODE REVIEW

**Comment by harshit98** [comment]
@niranjan94 how should I change the commit message? any source you can provide? thanks!

**Comment by niranjan94** [comment]
@harshit98 you can do a `git commit --amend` (amending the most recent commit) then do a `git push origin <branch_name> -f` (force push)

**Comment by harshit98** [comment]
@niranjan94 this never happened before, but why it is giving error? I did this - 
-  `git checkout patch-1`
-  `git commit --amend` 

and after that I get this - 

selection_029

**Comment by harshit98** [comment]
Done! Thank you @niranjan94 , learning a lot from you. :smile:

**Pull request merged**
