### PR TITLE
Fixing About page Our Team section ( For Small Screens )

### LINKED ISSUE #1446: Bad alignment of Team section in About page ( small screen )
**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Current behavior:**

Unresponsive for medium small and extra small screens

**Expected behavior**

Should be in the middle

**Screenshots of the issue:**

pr-1442-fossasia-susper surge sh_about pixel 2 xl

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1446

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Using Bootstrap classes with text-centre to align img with text in center for all type of screens

- https://pr-1445-fossasia-susper.surge.sh

- 
screenshot_2019-01-29-00-09-52-763_com android chrome

### CODE REVIEW

**Comment by subhahu123** [comment]
@praveenojha33 please review this

**Review by praveenojha33 — APPROVED** [review]
LGTM :+1:

**Comment by praveenojha33** [comment]
@AakashMallik @shreyanshdwivedi Please review.

**Review by Pipe-Runner — COMMENTED** [review]
LGTM but test coverage is dropping. Could you give it a look?

**Review by shreyanshdwivedi — APPROVED** [review]
LGTM :+1:

**Review by championpaddler — APPROVED** [review]

**Comment by praveenojha33** [comment]
@subhahu123 Please submit the tests ASAP in another PR.

**Comment by subhahu123** [comment]
@praveenojha33 tests for what ?

**Comment by praveenojha33** [comment]
@subhahu123 The code coverage is decreasing, some files are getting affected by the code please go through it and if possible write tests for it.
Thank You !!

**Pull request merged**
