### PR TITLE
Fixes #183 Add susper as standard search engine to Chrome

### LINKED ISSUE #183: Add feature "Make Standard Search Engine" to Front page
We already have a way to add susper as standard search engine to Firefox. Please implement the same for Chrome/Chromium.

screenshot from 2017-04-28 04-56-22

### PR DESCRIPTION
**Pull request by harshit98**
Resolves #183 

See also - #194 . In my previous PR, I faced a problem while solving conflicts and providing preview link. So created a new PR.

Preview link - <a href="https://harshit98.github.io/susper.com/">here</a>. Please ignore the `footer-navbar` issue, it has been raised due to recent pull merged. The commits which I have done in this PR, does not include any file regarding `footer-navbar`.  

Screenshots : 

Chrome/Chromium browser - 

89ec1052-2ea1-11e7-8c30-cfeafbf46c6d

Firefox -

8ee19014-2ea1-11e7-9107-cfbec4641d36

### CODE REVIEW

**Comment by harshit98** [comment]
@nikhilrayaprolu Let me check. Though, it is the same code.

**Comment by harshit98** [comment]
@nikhilrayaprolu Didn't find any solution. Can you please help? Thanks. Code is correct. It is the same as it was before.

**Comment by harshit98** [comment]
@nikhilrayaprolu creating a new `default.js` file separately, I don't know why it does not work. But, including the script in `index.html` works.

**Comment by nikhilrayaprolu** [comment]
image
check with these errors being raised on chrome. fixing these may solve the problem.

**Comment by harshit98** [comment]
@nikhilrayaprolu ok, I'll go through it. :+1:

**Comment by harshit98** [comment]
@nikhilrayaprolu Preview link <a href="https://harshit98.github.io/susper.com/">here</a>. 

What I did - 
- Revert back the changes as it was before and deleted the `scripts` folder from `assets` folder.
- did some modifications for chrome/chromium browser.

**Comment by harshit98** [comment]
@nikhilrayaprolu done! no more console errors. :smile:

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 are you able to install it on chrome. I am not able to install on my workstation.

**Comment by harshit98** [comment]
@isuruAb @nikhilrayaprolu I'll open up a issue regarding this if this is happening. In this PR, I have worked according to issue. The box was not appearing in chrome. This PR solves that problem. :smile:

**Pull request merged**
