### PR TITLE
Fixes #997:Added Yarn as Dependency Manager along with NPM

### LINKED ISSUE #997: Adding Yarn as a Dependency Manager along with NPM.
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**
Yarn is a dependency manager introduced by facebook . It is faster than npm and it can install dependencies even when the machine is offline. More about Yarn can be found here https://yarnpkg.com/en/

### PR DESCRIPTION
**Pull request by praveenojha33**
Fixes #997 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Added Yarn as dependency manager along with npm .

- https://pr-998-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by praveenojha33** [comment]
@simsausaurabh Please review .

**Comment by simsausaurabh** [comment]
@praveenojha33 please see https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn for reference. Yarn too uses node_modules. Including it in traivs just increases a check for travis that will look in future if there is any dependency break through any PR or not for yarn.

**Comment by praveenojha33** [comment]
@simsausaurabh Please review now. I updated travis after going through the blog.

**Comment by praveenojha33** [comment]
@mariobehling Please review

**Pull request merged**
