### PR TITLE
Adding sidebar

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
implemented filters for susper similar to susper-backbone.

### CODE REVIEW

**Comment by nikhilrayaprolu** [comment]
I have done removing the irrelevant commits but again a  new commit added due to merging of the angular branch into this. @niranjan94

**Comment by niranjan94** [comment]
@nikhilrayaprolu it shouldn't happen. Create a fresh branch off the `angular` branch and then cherrypick the `	adding sidebar` commit onto it

**Comment by nikhilrayaprolu** [comment]
@mariobehling @niranjan94 made it into 1 commit ,please review

**Comment by mariobehling** [comment]
Please provide a screenshot and link to sample page.

**Comment by nikhilrayaprolu** [comment]
@mariobehling the page is hosted at http://nikhilra.tk/ , please review it on firefox , it looks like there is some error with chrome for reading the url parameters. I am working on it now

**Comment by nikhilrayaprolu** [comment]
image

on clicking on elements they toggle
image

**Comment by nikhilrayaprolu** [comment]
@mariobehling ,this can be merged for now

**Comment by mariobehling** [comment]
As mentioned earlier on a few places, please do not follow the style of the old site anymore. What is the point in making a new site? The old site could work with backbone still. The new service with Angular also gives us a chance to redesign and follow more modern approaches like google.com and loklak.net. Please do not implement the old design anymore. Look for inspiration at google.com instead. 

Closing this PR therefore. Thank you.

**Comment by mariobehling** [comment]
Google has widgets on the right hand side of search pages. It also has the "tools" option on the top. Please open issues first and discuss changes there. Then create a pull request and match it with the issue. Provide a link to the relevant issue in the description, please. Cheers.

**Pull request closed without merging**
