### PR TITLE
Fix #1465 Removing unused imports from services and component

### LINKED ISSUE #1465: Remove unused  imports from components and services
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Currently , In some components and services , there are some unusable imports which is not used anywhere in those files. we should remove them they are not useful .

**Will work on the issue:**
yes

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1465 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- https://pr-1457-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by subhahu123** [comment]
@praveenojha33 review please

**Review by simsausaurabh — APPROVED** [review]

**Comment by simsausaurabh** [comment]
Also state the issue you are solving in your commit message and PR description.

**Review by sakshee-19 — APPROVED** [review]

**Review by praveenojha33 — COMMENTED** [review]
Please open an issue and than reference this PR. Please follow guidelines.

**Comment by subhahu123** [comment]
> Please open an issue and than reference this PR. Please follow guidelines.

Done

**Review by praveenojha33 — APPROVED** [review]

**Comment by praveenojha33** [comment]
Please rebase your branch.

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
Resolve conflicts, then it will be good to go.

**Review by simsausaurabh — COMMENTED** [review]
There are still conflicts.

**Comment by praveenojha33** [comment]
@subhahu123 Please remove conflicts.

**Pull request closed without merging**
