### PR TITLE
Number input fields only accept number inputs

### LINKED ISSUE #1355: Change type of number input fields in Advanced Search
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Currently, their type is `text`, which should be changed to `number`.

**Expected behavior:**

The type of input field should be changed to `number`.

**Screenshots of the issue:**

screenshot 2018-12-28 at 3 49 06 pm

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by neeraj3029**
Fixes #1355 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Added Surge preview link

#### Changes proposed in this pull request:
The type of input fields (`numbers ranging from`) in Advanced Search that can only accept numbers is changed to `number`, so that they accept only number input.
 

- https://pr-1356-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please resolve conflicts.

**Comment by neeraj3029** [comment]
@simsausaurabh @bhaveshAn @mariobehling I've resolved the conflicts.

**Comment by neeraj3029** [comment]
Thanks @sakshee-19, the second commit is a branch-merge, so I think it can't be squashed.

**Comment by neeraj3029** [comment]
@praveenojha33 There are no conflicts with the base branch in this pull request, I suppose it can be merged.

**Comment by neeraj3029** [comment]
@mariobehling @simsausaurabh Please merge.

**Comment by praveenojha33** [comment]
@neeraj3029 Merging is disabled until and unless there are conflicts.
image

**Comment by neeraj3029** [comment]
@praveenojha33 It shows no conflicts here in this image 😅 , there must be some error. Should I make a new pull request?

screenshot 2019-01-14 at 9 46 03 pm

**Comment by shreyanshdwivedi** [comment]
@neeraj3029 commits can be squashed in this case too. I myself have experienced similar situation.
And the conflicts @praveenojha33 is mentioning about is due to the reason that you have 2 commits out of which one is for merging different branch into this PR.

**Comment by neeraj3029** [comment]
@praveenojha33 I'm closing this PR to make a new one.

**Pull request closed without merging**
