### PR TITLE
Fixes #604 suggestion box aligned properly at all sizes

### LINKED ISSUE #604: Mobile compatibility: Align search bar and suggestion box properly
**Actual Behaviour**

In Susper the search and suggestion box are not properly aligned they mismatch, and even overlap with the logo.

**Expected Behaviour**

The design should be neat and the boxes should be aligned like in loklak

**Screenshots of the issue**
image
image

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #604 

Changes:suggestion box aligned with search bar properly at all sizes

Demo Link: [https://marauderer97.github.io/susper.com/](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 
image
image
image
image
image

@harshit98 Again, since you set the width of the nav input from the .ts file, in #621 I have set the width in css equivalent to results page, and set it through .ts file in index component. please verify. Also note that although you hard coded 536px to be nav-input size through out, I retained it only till 652px, after which for the sake of responsiveness I changed it in terms of viewport width

### CODE REVIEW

**Comment by harshit98** [comment]
At `995px` dropdown is hidden.
screenshot from 2017-07-12 18-37-09

At `815px` it again appears.
screenshot from 2017-07-12 18-37-36

It would be better at `815px` you should hide dropdown and at `995px` dropdown should appear.

Also on `815px`, the suggestion box is still not aligned properly.
screenshot from 2017-07-12 18-39-46

At `638px` and `509px`, there is a solid line appearing in the suggestion box.
screenshot from 2017-07-12 18-42-25

Rest all looks good to me. Good work @Marauderer97 :+1: : )
Kindly go through requested changes.

**Comment by Marauderer97** [comment]
@harshit98 Dropdown alignment is not a part of this PR, please read the description of the issue, I have not made any changes to the drop down icon position.
Will go through the rest of the requested changes

**Comment by harshit98** [comment]
@Marauderer97 #603 Here you made dropdown responsive on _results page_ but, in this PR - I'm observing at `995px` dropdown is getting hidden and at `815px` it again appears. 

- When I reviewed #603 everything was fine related to drop-down menu. Kindly look where is the issue happening.

**Comment by Marauderer97** [comment]
@harshit98 True, the dropdown icon should have been adjusted after the search bar and suggestion box, now all its values, in terms of left margin will have to be re written, I will make a seperate PR for it, meanwhile I have fixed all the other glitches you mentioned, please verify, there is no black line any longer, and I have tried adjusting the autocorrect as accurately as possible, as efficiently as possible, without makin g a mess of the code.

**Pull request merged**
