### PR TITLE
Fixes #705, Makes intelligence component responsive

### LINKED ISSUE #705: Make the intelligence component responsive.
**Actual Behaviour**

When intelligence component responds, the width of box crosses the screen size.

**Expected Behaviour**

It should be responsive and should be equal to the width of screen size to avoid white space issue.

**Screenshots of the issue**

screenshot from 2017-08-03 08-03-27

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #705 

Changes: Makes intelligence component responsive

Demo Link:[https://marauderer97.github.io/susper.com/](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 

image
image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Can travis please be deployed for this? There is a problem with the updation of the demo link

**Comment by harshit98** [comment]
What is happening while generating preview link? Conflicts?

**Comment by Marauderer97** [comment]
@harshit98 Since I cherry-pick from old commits and my commit on Large screens is very old, the entire thing is getting very messy, and yes conflicts arise too
@nikhilrayaprolu Thank you

**Comment by Marauderer97** [comment]
@nikhilrayaprolu @harshit98 Kindly review

**Comment by Marauderer97** [comment]
@harshit98 Do you want me to change the @media tag to 475px? The default width was 434px for intelligence. That is why around 450, since the box starts getting hidden I made the box relative to viewport width.

**Comment by harshit98** [comment]
Use Chrome's responsiveness feature which gives the best idea of how a website will look on different size of devices.

**Comment by Marauderer97** [comment]
@harshit98 I am trying to follow loklak.net, where the responsive-ness is continuous and at all intermediate widths. If I put the tag at 425px like you suggest, this is what happens
image
The intelligence component exceeds screen width and causes extra white space. That is why I decided 450px is a more stable width.

**Pull request merged**
