### PR TITLE
Update ISSUE_TEMPLATE.md

### LINKED ISSUE #874: Improve Issue tEMPLATE
**I'm submitting a ...**
- [ ] bug report
- [ X] feature request

**Current behavior:**
lacking info

**Expected behavior:**

info added
**Screenshots of the issue:**

I am workin g pls dont without my consent

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes #874 
Added needed info

### CODE REVIEW

**Comment by samyakbvs** [comment]
I don't think is required

**Comment by arjunpandey2003** [comment]
@samyakbvs it is in every issue template It should be here as well

**Comment by samyakbvs** [comment]
Mentors pls don't merge, I and Arjun are collaborating on this

**Comment by samyakbvs** [comment]
Will be committing shortly

**Comment by arjunpandey2003** [comment]
yes

**Comment by arjunpandey2003** [comment]
making something

**Pull request closed without merging**
