### PR TITLE
Fixes #664: Longer suggestions in related searches

### LINKED ISSUE #664: Related Searches: Issue with distribution of suggestions with longer suggestions
The suggestions are not distributed in one line anymore when a suggestion is longer than usual. Please ensure related searches show results in one line.

screenshot from 2017-07-18 10-34-09

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #664 

Changes: 
- Now longer suggestion in related searches appears clearly without any text wrapping.

Demo Link: https://harshit98.github.io/susper.com/

Screenshots for the change: 

screenshot from 2017-07-18 16-11-00

Kindly review @nikhilrayaprolu @Marauderer97

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 I am not able to view any results in your test link
image
However, it appears in Susper immediately:
image

**Comment by harshit98** [comment]
@Marauderer97 I don't know why GitHub page is not working on Chrome. Try in Firefox. It is working fine.

**Comment by Marauderer97** [comment]
@harshit98 I'm sorry, I am still not able to see results,
image
 can you please include screenshots of related searches for queries of different lengths, at different window sizes? (to make sure the changes you made are mobile-friendly)

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 disable protection
image

**Comment by Marauderer97** [comment]
@harshit98 Please look into errors caused like this
image

**Comment by harshit98** [comment]
ok @Marauderer97 working on it.

**Comment by harshit98** [comment]
@Marauderer97 Done.
screenshot from 2017-07-19 20-15-21
screenshot from 2017-07-19 20-14-55
screenshot from 2017-07-19 20-15-11

**Comment by Marauderer97** [comment]
@harshit98 Looks much better, but sometimes the space between the 2 columns seems too much, this is how it looks in Google:
image
Are there any tricks we can use to get a similar look?

**Pull request merged**
