### PR TITLE
addition of sidebar

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
implemented filters for susper similar to susper-backbone.
**can be merged now**

### CODE REVIEW

**Comment by mariobehling** [comment]
@nikhilrayaprolu Thanks, but let's talk about the design of this page. The goal would be to implement a design closer to google than to the old susper design with the sidebar.

**Comment by nikhilrayaprolu** [comment]
resolved #16 and #5 
@mariobehling can be merged now

**Comment by niranjan94** [comment]
@nikhilrayaprolu sidebar is completely unrelated to #16 and #5 . Please create a separate PR for those two tasks and let this PR contain only the sidebar since that is still pending discussion.

**Comment by nikhilrayaprolu** [comment]
@niranjan94 resolving #16 made the implementation of #5 easier ,hence I made solved both issues in one pull request. please review it.

**Comment by niranjan94** [comment]
@nikhilrayaprolu I meant ... Don't mix #16 and #5 in this sidebar PR

**Comment by mariobehling** [comment]
Closing this then. Please re-open when relevant. Thank you.

**Pull request closed without merging**
