### PR TITLE
Fixing Overlapping Of Description in Results

### LINKED ISSUE #1300: query_description is not perfectly aligned
**Current behavior:**
screenshot from 2018-12-14 21-10-11
screenshot_2018-12-14 susper - decentral search engine

untitled
**Expected behavior:**
screenshot_2018-12-14 susper - decentral search engine 1

**Will work on the issue:**
yes

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1300 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Removing the negative sign of margin-top

#### Preview Link
- https://pr-1313-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by subhahu123** [comment]
please review
now it's working

**Comment by subhahu123** [comment]
@praveenojha33
Please review

**Comment by praveenojha33** [comment]
Changes do not work in chrome
image

**Comment by praveenojha33** [comment]
Changes in this PR is not working for me.
image

**Comment by subhahu123** [comment]
screenshot from 2018-12-22 14-24-37

**Pull request closed without merging**
