### PR TITLE
Fixes #182, Search bar responsive to all window widths

### LINKED ISSUE #182: Ensure Logo and Search Bar are centered
The start page shows a logo/bar that is not centered.

Expected: Elements should be centered.

### PR DESCRIPTION
**Pull request by Marauderer97**
Screenshots at various sizes:
image
image
image
image

### CODE REVIEW

**Comment by daminisatya** [comment]
Even for mobiles?

**Comment by harshit98** [comment]
@Marauderer97 Please check the screenshots. Desktop view has been disturbed.

**Comment by Marauderer97** [comment]
image
@harshit98 I donot see any problem for all screen sizes. Can you mention your browser and screen size?

**Comment by Marauderer97** [comment]
@harshit98 @isuruAb @daminisatya I see it now. The update branch caused this. That is why I couldn't see it locally. This isn't from this PR. susper.com already has this. Look:
image
Some recently merged pr must have caused this.

**Comment by harshit98** [comment]
@Marauderer97 Browser : Google Chrome, Screen-size : 1326 x 455. I have posted the screenshot, what I see on heroku deployment. Also, please see your screenshot. The 'line' is again seems to be appearing below search bar.

**Comment by Marauderer97** [comment]
@harshit98 My screenshot has the line, since i started working on the bug, before my last PR was merged :smile:

**Comment by mariobehling** [comment]
Ok, let's iterate step by step. Please help to fix open points. I am merging this then. Cheers.

**Pull request merged**
