### PR TITLE
Updated issue template and added a sister project

### LINKED ISSUE #874: Improve Issue tEMPLATE
**I'm submitting a ...**
- [ ] bug report
- [ X] feature request

**Current behavior:**
lacking info

**Expected behavior:**

info added
**Screenshots of the issue:**

I am workin g pls dont without my consent

### LINKED ISSUE #879: Add more sister projects
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

less projects
**Expected behavior:**

more added
**Screenshots of the issue:**

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes #874 
Fixes #879

### CODE REVIEW

**Comment by harshit98** [comment]
@arjunpandey2003 Preview link? Please go through readme file to get preview link.

**Comment by arjunpandey2003** [comment]
hey @harshit98 since I don't have github desktop(my original laptop is gone for repair and my net is exhausted) and changes were made online, I cant clone to desktop pls accept like that I will try to download dektop thanks hope you understand. Please judge on the code change basis

**Comment by arjunpandey2003** [comment]
hey @harshit98 since I don't have github desktop(my original laptop is gone for repair and my net is exhausted) and changes were made online, I cant clone to desktop pls accept like that I will try to download desktop thanks hope you understand. Please judge on the code change basis

**Comment by harshit98** [comment]
@arjunpandey2003 Have you gone through my comment carefully?

**Comment by arjunpandey2003** [comment]
https://pr-880-fossasia-susper.surge.sh/ @harshit98

**Comment by arjunpandey2003** [comment]
@harshit98 given my preview link, pls take a look

**Comment by arjunpandey2003** [comment]
pls merge

**Pull request closed without merging**
