### PR TITLE
Fixes #759 search results from browser address bar

### LINKED ISSUE #759: Search results from browser address bar/ search box not following standard
If the user has Susper as standard search engine installed and puts in searches into the address bar in Chrome/Fx or search box in Firefox the search performed is "searchterm+searchterm" instead of "searchterm searchterm".

screenshot from 2017-08-23 10-40-28

### PR DESCRIPTION
**Pull request by collinx**
Fixes issue #759

Changes: 
Replaced the query with the standard query.

Demo Link: [Susper.com](https://susperdeploy.firebaseapp.com)

### CODE REVIEW

**Comment by soumam007** [comment]
@collinx 
just a doubt , say we make susper.com default search engine and in the address bar we give the query "2+3" then in the query box it should write "2+3" as in google.com but i guess if your code works correctly then , 2+3 in address bar will give "2 3" in query box.

**Comment by collinx** [comment]
@soumam007 that is right but if you search either of `2 3` or `2+3`, it will give same results in susper. Thatswhy, it would not matter.

**Comment by harshit98** [comment]
@collinx Please fix Travis issues which are occurring.

**Comment by collinx** [comment]
@harshit98 this PR will pass the Travis CI build once #784 will be merged and #783 is solved.

**Comment by collinx** [comment]
@harshit98 Travis issues are fixed, check now. 😄

**Pull request merged**
