### PR TITLE
Fixing the infobox

### LINKED ISSUE #1399: Fixes in infobox
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

There are a number of bugs in infobox
- The links should initially have a blue color and underline upon hover similar to google
- Include twitter and google icons near share to,  similar to google.

**Screenshots of the issue:**

screenshot from 2019-01-10 00-08-25

**Will work on the issue:**
Yes

### PR DESCRIPTION
**Pull request by subhahu123**
Fixes #1399 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

-

- https://pr-1405-fossasia-susper.surge.sh

-

### CODE REVIEW

**Comment by subhahu123** [comment]
i was working on this but the travis is failing why @shreyanshdwivedi

**Comment by shreyanshdwivedi** [comment]
@subhahu123 the travis failure log clearly states the error `Unexpected closing tag "p"`. Read out the error log, you have placed unexpected paragraph tag

**Comment by subhahu123** [comment]
@shreyanshdwivedi  i have already gone through it but if u see my changes i have chages any paragraph closing tags

**Comment by subhahu123** [comment]
@praveenojha33  why travis is failing

**Comment by shreyanshdwivedi** [comment]
@subhahu123 I think your file is not following proper linting rules. The placement of `</p>` is not accurate. 
You can use https://dirtymarkup.com/ to check if your file is properly linted or not :)

**Comment by subhahu123** [comment]
@shreyanshdwivedi   
please check this
screenshot from 2019-01-15 16-52-49

After changing `</p> to <p/>`
it is working but why if u see above paragraph tags it uses same method

screenshot-www 10bestdesign com-2019 01 15-16-54-07

**Review by sakshee-19 — CHANGES_REQUESTED** [review]
Squash your commits and fix travis build.

**Comment by simsausaurabh** [comment]
Closing this due to inactivity. Follow up later.

**Pull request closed without merging**
