### PR TITLE
Adding to #206, Repositions the footer

### PR DESCRIPTION
**Pull request by Marauderer97**
image
image

Fixes the footer position without using bootstrap classes, addresses issue mentioned in #206 . @nikhilrayaprolu Chose this method to bootstrap classes, to avoid the hamburger icon, and match loklak.net design. Any suggestions/comments?

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 I believe it looks better now?
image

**Comment by harshit98** [comment]
No I mean the 2nd screenshot. Result section.

**Comment by mariobehling** [comment]
@Marauderer97 Please provide a link to a test page.

**Comment by Marauderer97** [comment]
@harshit98 updated screenshots
image
image
 
@mariobehling Test link: https://marauderer97.github.io/susper.com/

**Comment by mariobehling** [comment]
I am squashing commits. Please do this in future. Thanks!

**Pull request merged**
