### PR TITLE
src/app/about/about.component.html: Formats code

### PR DESCRIPTION
**Pull request by abishekvashok**
Addresses #834 

#### Checklist
- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:
Formats and intends code in `src/app/about.component.html`.
Consistently intends the code with 2 white spaces.

Signed-off-by: Abishek V Ashok

### CODE REVIEW

**Comment by harshit98** [comment]
@abishekvashok Can you remove the `package-lock.json` file?

**Comment by abishekvashok** [comment]
@harshit98 sure

**Comment by abishekvashok** [comment]
@harshit98 sorry it was mistake, done now!

**Comment by abishekvashok** [comment]
@fossasia/susper @fossasia/susper-admin please review

**Comment by abishekvashok** [comment]
@daminisatya thank you

**Pull request merged**
