### PR TITLE
Fixes #608: Align dropdown menu properly on homepage

### LINKED ISSUE #608: Align dropdown menu properly on homepage
**Actual Behaviour**

screenshot from 2017-07-07 14-26-02

dropdown menu not aligned properly on the homepage.

**Expected Behaviour**

screenshot from 2017-07-07 14-28-04

should be aligned w.r.t market leader. Also, fix responsiveness issue of drop-down menu on the homepage as well.
This issue can be referred here : #524

### PR DESCRIPTION
**Pull request by harshit98**
Fixes issue #608 

Changes: 
- fixed dropdown position on the homepage.
- fixes homepage responsiveness for the dropdown menu.

Demo Link: https://harshit98.github.io/susper.com/

Screenshots for the change: 

(Not appropriate here)

Kindly review @Marauderer97 @nikhilrayaprolu

### CODE REVIEW

**Comment by harshit98** [comment]
Done @mariobehling 

screenshot from 2017-07-09 02-04-11

**Comment by mariobehling** [comment]
Button not visible on mobile.

screenshot_2017-07-09-12-49-52

**Comment by mariobehling** [comment]
This is how google looks like

screenshot_2017-07-09-12-51-08

**Comment by harshit98** [comment]
@mariobehling working on it.

@Marauderer97 @nikhilrayaprolu When the screen size is `767px`, suddenly drop down menu hides away. I'm facing a problem. I tried some solutions, but it is not working. It would be great if you check what problem is occurring.

**Comment by Marauderer97** [comment]
@harshit98 It doesn't disappear. Since its original design requires a margin from the left, it is doing that and hence doesnot appear on the screen. I think changing the left margin values will fix this. However please keep in mind that you donot disrupt the results page alignment of dropdown in the process

**Comment by harshit98** [comment]
There are some issues because of some recent changes. I will make a fresh PR solving this issue. :+1:

**Pull request closed without merging**
