### PR TITLE
Fixes #181 get an info box on right

### LINKED ISSUE #181: How can we get an info box on the right
Duckduckgo and Google often show a sidebox with additional results mainly from Wikipedia. How can we get the same?

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
in reference to issue #181 made an info box to show results on right side.

image

image

demolink:- https://nikhilrayaprolu.github.io/susper.com-1/

### CODE REVIEW

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Travis is failing ,please check.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu The test link doesnot seem to work,
image
image

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 
image

it's working

**Comment by mariobehling** [comment]
@nikhilrayaprolu Great! Let's iterate from here and get the design closer as well.

**Pull request merged**
