### PR TITLE
Fixed overlapping footer, #1216

### LINKED ISSUE #1216: Overlapping!
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The bottom of every page overlapping couldn't be seen due to the footer. 
image
image

**Expected behavior:**
Resolve it.

# I'm working on this.

### PR DESCRIPTION
**Pull request by STEdirisuriya**
Fixes #1216

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:
Fixed overlapping footer.
- https://pr-1224-fossasia-susper.surge.sh

### CODE REVIEW

**Comment by Ryan10145** [comment]
@STEdirisuriya The Settings -> Advanced Search still has issues
screen shot 2018-11-17 at 10 59 39 pm

Also, on all of the pages, there is a good amount of space between the last line of text and the footer, yet in Privacy, there is little to no space, which is inconsistent. See the below screenshots.

Terms:
screen shot 2018-11-17 at 11 02 10 pm
Contact:
screen shot 2018-11-17 at 11 02 14 pm

Privacy:
screen shot 2018-11-17 at 11 02 18 pm

**Comment by STEdirisuriya** [comment]
@rajvaibhavdubey @Ryan10145 I updated it again. Could you please check it now?

**Comment by Ryan10145** [comment]
@STEdirisuriya LGTM :+1:

**Comment by STEdirisuriya** [comment]
@jogendra I have fixed it too. Please, could you check it now?

**Comment by abishekvashok** [comment]
Task link: https://codein.withgoogle.com/dashboard/task-instances/6162125815808000/

**Pull request merged**
