### PR TITLE
Fixes #589 speech UI changed

### LINKED ISSUE #589: Improve speech to text on search interface
Activating voice results in a continuous activated microphone. Please test the feature on the market leader page and adapt Susper to work in a similar way. First Google shows a screen with "Speak Now" and outputs the first info in voice when there is a sidebar box, e.g. "According to Wikipedia...".

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
Fixes issue #589 

Demo Link: https://susper-pr-624.herokuapp.com/

For whole working of this feature check this video https://www.youtube.com/watch?v=q1Zy-APxvs4

giphy

### CODE REVIEW

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Please check why travis is failing

**Comment by nikhilrayaprolu** [comment]
image

@mariobehling done.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 travis fixed

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by mariobehling** [comment]
Ok, I am merging this as work in progress. Let's try it on the live site. I think there are still issues.

**Pull request merged**
